### ISSUE TITLE
ncdirect API issues

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1248] opened 2020-12-24 13:18 UTC
1. `ncdirect_render_frame` & `ncdirect_raster_frame` are referenced in `ncdirect_render_image` as alternatives, but those are not public functions.
2. if `ncdirect_[b|f]g_*` are used to set values, maybe they should be renamed to include the word `set` like for ncplane, nccell, etc.

**Comment by dankamongmen** [comment] 2020-12-25 17:34
1) Are they not? How is `ncls` using them? They look public to me:

```
// Render an image using the specified blitter and scaling, but do not write
// the result. The image may be arbitrarily many rows -- the output will scroll
// -- but will only occupy the column of the cursor, and those to the right.
// To actually write (and free) this, invoke ncdirect_raster_frame().
API ncdirectv* ncdirect_render_frame(struct ncdirect* n, const char* filename,
                                     ncblitter_e blitter, ncscale_e scale);

// Takes the result of ncdirect_render_frame() and writes it to the output. The
// 'align', 'blitter', and 'scale' arguments must be the same as those passed
// to ncdirect_render_frame().
API int ncdirect_raster_frame(struct ncdirect* n, ncdirectv* faken,
                              ncalign_e align, ncblitter_e blitter,
                              ncscale_e scale);
```

2) Agreed. See #1247.

I'm going to close this as essentially a duplicate of #1247. Reopen if you disagree.

**Closed by dankamongmen** 2020-12-25 17:34 UTC
Labels: duplicate

**Comment by joseluis** [comment] 2020-12-25 18:33
Ups, thank you, I don't know why I didn't see them before.

**Comment by dankamongmen** [comment] 2020-12-28 07:27
Though, looking at it, these functions suck. `ncdirect_raster_frame()` ought not require `align`, `blitter`, or `scale`. Those ought be folded into `ncdirectv` and reproduced internally. I think I'm going to make this change.

**Comment by dankamongmen** [comment] 2020-12-28 07:41
Done.
