### ISSUE TITLE
rendering is left-aligned outside of TUI mode

### ISSUE THREAD

**Issue by michaelsbradleyjr** [dankamongmen/notcurses#2138] opened 2021-09-03 17:36 UTC
I tried local builds of v2.3.18 and current `master` branch, behaviors are the same either way. I also tried with v2.3.17 installed via homebrew and experienced the same.

![image](https://user-images.githubusercontent.com/194260/132044921-aa693f19-2c51-4a3a-9e29-5a13bac1ac28.png)

Terminal.app is on the left, iTerm2 is at the top-right and Kitty is on the bottom-right.

For all three, there is a message at the top of the output:
```
Error running xrandr --current 2>/dev/null (Invalid argument)
```

In Terminal.app, if I run `notcurses-info` after running `ncneofetch`, the terminal bell sounds and the output is only partial and garbled; need to `reset` after running `ncneofetch` in Terminal.app.

In Kitty, after running `ncneofetch` the cursor is hidden under the logo. Commands run after `ncneofetch` can have their output partially covered by the logo; need to `reset` after running `ncneofetch` in Kitty.

**Comment by dankamongmen** [comment] 2021-09-04 19:27
i think this is a duplicate of #2118, but since this has much better screencaps etc., i'll close that one in favor of this. thanks!

**Comment by dandee** [comment] 2021-09-09 12:31
I've also got the same error message. On top of that it incorrectly reports OS version as 11.4 (Big Sur) instead of 10.14 (Mojave):

<img width="899" alt="Screenshot 2021-09-09 at 14 19 54" src="https://user-images.githubusercontent.com/890495/132685975-92cc175b-7f3f-4e7a-8d14-c4b57212098f.png">

**Comment by dankamongmen** [comment] 2021-09-10 04:29
ooooh yes, the "Big Sur" is hardcoded at the moment, as that was the only macOS available to me. i'll make that a new bug, one which i ought be able to knock out immediately.

**Comment by dankamongmen** [comment] 2021-09-13 02:01
really wanted to get to this in 2.4.1, but it looks like it'll have to be the first fix in 2.4.2, as i'm about to cut 2.4.1.

**Comment by dankamongmen** [comment] 2021-09-13 04:23
so it looks like we have multiple problems here:

* we're not centering the logo
* the image isn't scrolling sufficiently (this is why the info box is too far up)
* don't try to run `xrandr` on mac/windows
* logo is occluding palette

**Comment by dankamongmen** [comment] 2021-09-13 04:24
none of this happens, of course, when i ssh into the macmini =] i'll get up on a rdc session when i can.

**Comment by dankamongmen** [comment] 2021-09-20 01:47
might #2095 help us out here? unsure whether it's applicable.

**Comment by dankamongmen** [comment] 2021-09-20 03:13
so yeah it seems we're sticking the logo on the left no matter what, despite using `NCVISUAL_OPTION_HORALIGNED` together with `NCALIGN_CENTER`. this is more obvious on mac because it has such a square logo.

**Comment by dankamongmen** [comment] 2021-09-20 03:15
yeah and we also see this with `ncplayer -k` (though not without the `-k`).

**Comment by dankamongmen** [comment] 2021-09-20 03:15
that's interesting, because `ncdirect -k` is using direct mode, whereas `ncneofetch` is using CLI mode....strange!

**Comment by dankamongmen** [comment] 2021-09-20 03:16
except it's not always, because `ncls` manages to put stuff on the right with no problem!

**Comment by dankamongmen** [comment] 2021-09-20 03:18
![2021-09-19-231747_851x1417_scrot](https://user-images.githubusercontent.com/143473/133953990-4df6c25d-b4cc-4814-a91c-a8b311077873.png)

yeah, explain that

**Comment by dankamongmen** [comment] 2021-09-20 03:19
same thing on macos
![2021-09-19-231903_1948x1414_scrot](https://user-images.githubusercontent.com/143473/133954042-17ee4614-bdc1-49e4-a4f2-03b0afbe40ef.png)

**Comment by dankamongmen** [comment] 2021-09-20 03:31
so we have:

* ncplayer: aligns properly for both pixel and cell
* ncplayer -k: aligns properly for cell, but not pixel **direct mode**
* ncls: always aligns properly **direct mode**
* ncneofetch: always misaligns with SCALE, but *not* with NONE **cli mode**

ugh

**Comment by dankamongmen** [comment] 2021-09-20 03:34
looking at the output of `ncneofetch`, were executing a hard `cups` to the first row before both the display and presentation. the former is unnecessary; the second is necessary, but has the wrong target.

**Comment by dankamongmen** [comment] 2021-09-20 03:40
indeed, the move is the only thing between the load and presentation; it's coming from `rasterize_sprixels()` in the `SPRIXEL_LOADED` case:

`dU4HU=^[\^[[53;1H^[_Ga=p,i=3432810,p=1,q=2,`

**Comment by dankamongmen** [comment] 2021-09-20 03:42
and that move is indeed fouled up, assuming the plane isn't somehow wider than the sprixel...let me check....
```
notcurses_rasterize_inner:1234:Sprixel phase 2                                             
 -------------------------- notcurses debug state -----------------------------            
  *************************   0x55c864e834d0 pile ****************************             
0000 off y:  56 x:   2 geom y:   8 x:  72 curs y:   0 x:  46 0x55c864e85ba0 info           
 bound 0x55c864e6ffe0 ← 0x55c864e70050 → 0x7fa00801d160 binds (nil)                        
0001 off y:  45 x:   0 geom y:  12 x:  68 curs y:   0 x:   0 0x7fa00801d160 bmap           
 bound 0x55c864e6ffe0 ← 0x55c864e85c00 → (nil) binds (nil)                                 
0002 off y:   0 x:   0 geom y:  64 x:  77 curs y:  63 x:   0 0x55c864e6ffe0 std            
 bound 0x55c864e6ffe0 ← 0x55c864e834e0 → (nil) binds 0x55c864e85ba0                        
 ______________________________________________________________________________            
GOING TO 45 0 for SPRITE                      
```

our `bmap` plane is 12 tall and 68 wide on a 77-wide terminal. it is located at...45,0. so yeah, it's placement of our plane that is the issue. we're rendering correctly.

**Comment by dankamongmen** [comment] 2021-09-20 03:43
ugh what's this doing in `display_thread()`?

`        ncplane_move_yx(iplane, y, 0);         `

=[ stupid dumb asshole

**Comment by dankamongmen** [comment] 2021-09-20 03:43
woo-hoo, that fixes it in `ncneofetch`!

**Comment by dankamongmen** [comment] 2021-09-20 03:44
ahhhh yes this is zee perfectness for `ncneofetch`, looks verah nice

**Comment by dankamongmen** [comment] 2021-09-20 03:45
she is looking perfect on zee mac now, also!

**Comment by dankamongmen** [comment] 2021-09-20 03:52
but `ncplayer -k` is still putting them in the wrong place, of course (that fix was limited to `ncneofetch`)...

**Comment by dankamongmen** [comment] 2021-09-20 03:53
let's create a new bug on that. i might go ahead and rewrite `ncplayer -k` to use CLI mode.

**Closed by dankamongmen** 2021-09-20 03:53 UTC
Labels: bug, macOS

**Comment by dankamongmen** [comment] 2021-09-20 11:08
hrmm we still have a problem when run in a kitty on mac that is significantly wider than it is tall, and we run from the top

![2021-09-20-070834_1466x1417_scrot](https://user-images.githubusercontent.com/143473/133992700-18f950c6-82fc-4782-988f-9b09c21315d8.png)

**Comment by dankamongmen** [comment] 2021-09-20 11:11
```
[cobra-la](0) $ cat e
SCROLLING UP 5
 -------------------------- notcurses debug state -----------------------------
  *************************   0x7f85e8d21370 pile ****************************
0000 off y:   0 x:  14 geom y:  64 x: 105 curs y:   0 x:   0 0x7f85e8c0c410 bmap
 bound 0x7f85e8d212a0 ← 0x7f85e8d21310 → 0x0 binds 0x0
0001 off y:   0 x:   0 geom y:  64 x: 133 curs y:  10 x:   0 0x7f85e8d212a0 std
 bound 0x7f85e8d212a0 ← 0x7f85e8d21380 → 0x0 binds 0x7f85e8c0c410
 ______________________________________________________________________________
[cobra-la](0) $ ./ncneofetch  2>e
```

**Comment by dankamongmen** [comment] 2021-09-20 11:12
yeah we ought be putting the infoplane significantly further down:

```
SCROLLING UP 5
 -------------------------- notcurses debug state -----------------------------
  *************************   0x7fb10440a040 pile ****************************
0000 off y:   0 x:  14 geom y:  64 x: 105 curs y:   0 x:   0 0x7fb10440ddb0 bmap
 bound 0x7fb10440a4d0 ← 0x7fb10440a540 → 0x0 binds 0x0
0001 off y:   0 x:   0 geom y:  64 x: 133 curs y:  10 x:   0 0x7fb10440a4d0 std
 bound 0x7fb10440a4d0 ← 0x7fb10440a050 → 0x0 binds 0x7fb10440ddb0
 ______________________________________________________________________________
 -------------------------- notcurses debug state -----------------------------
  *************************   0x7fb10440a040 pile ****************************
0000 off y:  10 x:  30 geom y:   8 x:  72 curs y:   7 x:  72 0x7fb1045210a0 info
 bound 0x7fb10440a4d0 ← 0x7fb10440a540 → 0x7fb10440ddb0 binds 0x0
0001 off y:   0 x:  14 geom y:  64 x: 105 curs y:   0 x:   0 0x7fb10440ddb0 bmap
 bound 0x7fb10440a4d0 ← 0x7fb104521100 → 0x0 binds 0x0
0002 off y:   0 x:   0 geom y:  64 x: 133 curs y:  10 x:   0 0x7fb10440a4d0 std
 bound 0x7fb10440a4d0 ← 0x7fb10440a050 → 0x0 binds 0x7fb1045210a0
 ______________________________________________________________________________
[cobra-la](0) $ 
```

**Comment by dankamongmen** [comment] 2021-09-20 11:12
the image is 59 tall

**Comment by dankamongmen** [comment] 2021-09-20 11:15
we're placing the infoplane wherever the cursor is on the standard plane. 

working (from bottom):
```
 -------------------------- notcurses debug state -----------------------------
  *************************   0x7f9430820e40 pile ****************************
0000 off y:   0 x:  14 geom y:  64 x: 105 curs y:   0 x:   0 0x7f942f40c2f0 bmap
 bound 0x7f9430820d70 ← 0x7f9430820de0 → 0x0 binds 0x0
0001 off y:   0 x:   0 geom y:  64 x: 133 curs y:  63 x:   0 0x7f9430820d70 std
 bound 0x7f9430820d70 ← 0x7f9430820e50 → 0x0 binds 0x7f942f40c2f0
 ______________________________________________________________________________
SCROLLING UP 63
 -------------------------- notcurses debug state -----------------------------
  *************************   0x7f9430820e40 pile ****************************
0000 off y:   0 x:  14 geom y:  64 x: 105 curs y:   0 x:   0 0x7f942f40c2f0 bmap
 bound 0x7f9430820d70 ← 0x7f9430820de0 → 0x0 binds 0x0
0001 off y:   0 x:   0 geom y:  64 x: 133 curs y:  63 x:   0 0x7f9430820d70 std
 bound 0x7f9430820d70 ← 0x7f9430820e50 → 0x0 binds 0x7f942f40c2f0
 ______________________________________________________________________________
 -------------------------- notcurses debug state -----------------------------
  *************************   0x7f9430820e40 pile ****************************
0000 off y:  63 x:  30 geom y:   8 x:  72 curs y:   7 x:  72 0x7f942f7042b0 info
 bound 0x7f9430820d70 ← 0x7f9430820de0 → 0x7f942f40c2f0 binds 0x0
0001 off y:   0 x:  14 geom y:  64 x: 105 curs y:   0 x:   0 0x7f942f40c2f0 bmap
 bound 0x7f9430820d70 ← 0x7f942f704310 → 0x0 binds 0x0
0002 off y:   0 x:   0 geom y:  64 x: 133 curs y:  63 x:   0 0x7f9430820d70 std
 bound 0x7f9430820d70 ← 0x7f9430820e50 → 0x0 binds 0x7f942f7042b0
 ______________________________________________________________________________
SCROLLING UP 7
 -------------------------- notcurses debug state -----------------------------
  *************************   0x7f9430820e40 pile ****************************
0000 off y:  56 x:  30 geom y:   8 x:  72 curs y:   0 x:  44 0x7f942f7042b0 info
 bound 0x7f9430820d70 ← 0x7f9430820de0 → 0x7f942f40c2f0 binds 0x0
0001 off y:  -7 x:  14 geom y:  64 x: 105 curs y:   0 x:   0 0x7f942f40c2f0 bmap
 bound 0x7f9430820d70 ← 0x7f942f704310 → 0x0 binds 0x0
0002 off y:   0 x:   0 geom y:  64 x: 133 curs y:  63 x:   0 0x7f9430820d70 std
 bound 0x7f9430820d70 ← 0x7f9430820e50 → 0x0 binds 0x7f942f7042b0
 ______________________________________________________________________________
[cobra-la](0) $ 
```

from top:

```
 -------------------------- notcurses debug state -----------------------------
  *************************   0x7f9767c09f70 pile ****************************
0000 off y:   0 x:  14 geom y:  64 x: 105 curs y:   0 x:   0 0x7f9767c0e0b0 bmap
 bound 0x7f9767c0acf0 ← 0x7f9767c0ad60 → 0x0 binds 0x0
0001 off y:   0 x:   0 geom y:  64 x: 133 curs y:   5 x:   0 0x7f9767c0acf0 std
 bound 0x7f9767c0acf0 ← 0x7f9767c09f80 → 0x0 binds 0x7f9767c0e0b0
 ______________________________________________________________________________
SCROLLING UP 5
 -------------------------- notcurses debug state -----------------------------
  *************************   0x7f9767c09f70 pile ****************************
0000 off y:   0 x:  14 geom y:  64 x: 105 curs y:   0 x:   0 0x7f9767c0e0b0 bmap
 bound 0x7f9767c0acf0 ← 0x7f9767c0ad60 → 0x0 binds 0x0
0001 off y:   0 x:   0 geom y:  64 x: 133 curs y:  10 x:   0 0x7f9767c0acf0 std
 bound 0x7f9767c0acf0 ← 0x7f9767c09f80 → 0x0 binds 0x7f9767c0e0b0
 ______________________________________________________________________________
 -------------------------- notcurses debug state -----------------------------
  *************************   0x7f9767c09f70 pile ****************************
0000 off y:  10 x:  30 geom y:   8 x:  72 curs y:   7 x:  72 0x7f9750204080 info
 bound 0x7f9767c0acf0 ← 0x7f9767c0ad60 → 0x7f9767c0e0b0 binds 0x0
0001 off y:   0 x:  14 geom y:  64 x: 105 curs y:   0 x:   0 0x7f9767c0e0b0 bmap
 bound 0x7f9767c0acf0 ← 0x7f97502040e0 → 0x0 binds 0x0
0002 off y:   0 x:   0 geom y:  64 x: 133 curs y:  10 x:   0 0x7f9767c0acf0 std
 bound 0x7f9767c0acf0 ← 0x7f9767c09f80 → 0x0 binds 0x7f9750204080
 ______________________________________________________________________________
 -------------------------- notcurses debug state -----------------------------
  *************************   0x7f9767c09f70 pile ****************************
0000 off y:  10 x:  30 geom y:   8 x:  72 curs y:   0 x:  44 0x7f9750204080 info
 bound 0x7f9767c0acf0 ← 0x7f9767c0ad60 → 0x7f9767c0e0b0 binds 0x0
0001 off y:   0 x:  14 geom y:  64 x: 105 curs y:   0 x:   0 0x7f9767c0e0b0 bmap
 bound 0x7f9767c0acf0 ← 0x7f97502040e0 → 0x0 binds 0x0
0002 off y:   0 x:   0 geom y:  64 x: 133 curs y:  10 x:   0 0x7f9767c0acf0 std
 bound 0x7f9767c0acf0 ← 0x7f9767c09f80 → 0x0 binds 0x7f9750204080
 ______________________________________________________________________________
```

**Comment by dankamongmen** [comment] 2021-09-20 11:25
ok i think i got it
