### ISSUE TITLE
visual render always fails after a visual resize

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1559] opened 2021-04-18 13:49 UTC
also coming from: https://github.com/dankamongmen/notcurses/issues/1546#issuecomment-821980361

Trying to render a visual after it's been resized fails, independently of the arguments passed. IIUC render(1, 1) should be a no-op, and even that causes an error.

I've made a simplifed example in rust named [issue-1559](https://github.com/dankamongmen/notcurses/blob/master/rust/examples/issue-1559.rs), based on the pixel-cell one.

**Comment by dankamongmen** [comment] 2021-04-18 15:01
Strange. It works following inflation though, right?

**Comment by joseluis** [comment] 2021-04-18 15:08
yes, it does work fine following inflation.

**Comment by dankamongmen** [comment] 2021-04-18 15:28
huh, you're right! that's what i get for not having any unit tests on it, huh.

**Comment by dankamongmen** [comment] 2021-04-18 15:31
wait, nevermind, it's working just fine for me. you're passing it pixel geometry, not cell geometry, right?

**Comment by joseluis** [comment] 2021-04-18 15:35
ops... I was thinking in cells... I'll try it later. now I'm about to take a nap. unlike you I need to sleep every now and then, lol.

**Comment by dankamongmen** [comment] 2021-04-18 15:38
thanks for all the help! i should clarify it in the documentation. enjoy your siesta

**Comment by joseluis** [comment] 2021-04-18 15:40
in ncvisual_resize says: Resize the visual so that it is 'rows' X 'columns'. I thought I had to tell it how many cells in rows and columns. But even if it's in pixels... I don't understand why it must give an error. What are the constrictions of a valid value? can't it downsize?

**Comment by dankamongmen** [comment] 2021-04-18 15:47
> in ncvisual_resize says: Resize the visual so that it is 'rows' X 'columns'. I thought I had to tell it how many cells in rows and columns. But even if it's in pixels... I don't understand why it must give an error. What are the constrictions of a valid value? can't it downsize?

totally agreed that this is a valid issue regardless of whether that fixes your use case, and i can reproduce that here

**Comment by dankamongmen** [comment] 2021-04-18 16:13
actually, nevermind, i had a bug in my test. i cannot reproduce this failure with `ncvisual_resize()`, at least not with my code. i might go take a look at yours. you might want to set `loglevel` high, as that area of code has a lot of diagnostics.

**Comment by joseluis** [comment] 2021-04-18 19:39
Ok so the size must be in pixels. And if the number of columns or rows is not equal or greater than the current ones, it fails. I've added that piece of information to the documentation.

In the future it would be good to update this function so that it also supports downsizing, I think. At least its name 'resize' seems to suggest that capability.

**Comment by dankamongmen** [comment] 2021-04-18 19:42
> Ok so the size must be in pixels. And if the number of columns or rows is not equal or greater than the current ones, it fails. I've added that piece of information to the documentation.
> 
> In the future it would be good to update this function so that it also supports downsizing, I think. At least its name 'resize' seems to suggest that capability.

no, it's working for me with downsizing! i'm going from 20x10 to 8x8 in my unit test, and it seems to work fine.

**Comment by dankamongmen** [comment] 2021-04-21 23:50
@joseluis any idea what the dissonance was here? do you want me to look at something?

**Comment by joseluis** [comment] 2021-04-22 00:00
I've not yet looked at this again, busy with other issues for the time being.

**Comment by dankamongmen** [comment] 2021-04-23 19:14
i think i might have actually reproduced your problem, and i think it's a function of terminal emulator X media backend, which is why i wasn't seeing it. the `visual` PoCPP is failing, and it comes down to a failure to scale in `ffmpeg_blit()`:

```
ncvisual_resize(0x5576b2a249c0, 140, 80, 0x7fff8982ab00) = 0
ncvisual_render(0x5576b2a24d00, 0x5576b2a249c0, 0x7fff8982ab30, 0INPUT N: 0x5576b2a54840
blit: 0x0:140+80 of 140/80 stride 320 0x5576b2b2d580
inframe: 0x5576b2b2a000 oframe: 0x5576b2b2a000 frame: 0x5576b2a6a780
got format: 26 want format: 26
place: 0/0 rows/cols: 140/80 140/80
HALF 140 X 80 @ 0 X 0 (0x5576b2b2d580) place: 0 X 0
I HAVE RENDERED 0x5576b2a54840
) = 0x5576b2a54840
notcurses_render(0x5576b2a24d00, 0, 0x7f8d241142c0, 0) = 0
clock_nanosleep(1, 0, 0x7fff8982aba0, 0)         = 0
ncplane_destroy(0x5576b2a54840, 0, 0, 0x7f8d2e194c0a) = 0
clock_nanosleep(1, 0, 0x7fff8982aba0, 0)         = 0
ncvisual_rotate(0x5576b2a249c0, 0, 0, 0x7f8d2e194c0a) = 0
ncvisual_render(0x5576b2a24d00, 0x5576b2a249c0, 0x7fff8982ab30, 0x5576b2a3bff0INPUT N: (nil)
blit: 0x0:80+140 of 80/140 stride 560 0x5576b2a54940
inframe: 0x5576b2b2a000 oframe: 0x5576b2b2a000 frame: 0x5576b2a6a780
got format: 26 want format: 26
resize+render: 140/80->80/140 (80/140)
Error applying scaling (140 X 80)
I HAVE RENDERED (nil)
) = 0
ncvisual_destroy(0x5576b2a249c0, 0, 0x7f8d241142c0, 0) = 0
notcurses_stop(0x5576b2a24d00, 7, 0, 0
```

**Comment by dankamongmen** [comment] 2021-04-23 19:54
yeah, kitty behaves differently. i think if we can get `visual` working again, your problem will be resolved, and you've identified a real regression. good work!

**Comment by dankamongmen** [comment] 2021-04-23 23:05
"[swscaler @ 0x556a6fa696c0] Slice parameters 0, 140 are invalid"

**Comment by dankamongmen** [comment] 2021-04-23 23:42
alright, I think I found the problem. fix incoming. if you could run your test again, i'd appreciate it!

**Comment by joseluis** [comment] 2021-04-24 00:23
yeah no, it still gives the same error for me

**Comment by dankamongmen** [comment] 2021-04-24 00:40
curses. what ought i be running to exercise it?

**Comment by joseluis** [comment] 2021-04-24 01:00
> I've made a simplifed example in rust named [issue-1559](https://github.com/dankamongmen/notcurses/blob/master/rust/examples/issue-1559.rs), based on the pixel-cell one.

`cargo run --example issue-1559`

**Comment by dankamongmen** [comment] 2021-04-24 04:20
huh, `ltrace` doesn't work on rust binaries, eh? even to trace c lib calls? lame

**Comment by dankamongmen** [comment] 2021-04-24 04:24
I'm now reproducing this in the `Bitmaps/SprixelResize` unit test, thanks much!

**Comment by dankamongmen** [comment] 2021-04-24 04:26
```c
[swscaler @ 0x55914bcedac0] Warning: data is not aligned! This can lead to a speed loss
ncplane_new_internal:341:Won't create denormalized plane (r=0, c=1)
```

**Comment by dankamongmen** [comment] 2021-04-24 04:28
so it looks like the resize to (1, 1) is turning this into a 0-row visual. and indeed, this same thing happened for (2, 2). using (9, 9) worked fine: 

```
on subsampled chroma
[swscaler @ 0x55cd63e996c0] Warning: data is not aligned! This can lead to a speed loss
ncplane_new_internal:444:Created new 1x1 plane "bmap" @ 0x0
```

  61 rows (23px) 80 cols (11px)

**Comment by dankamongmen** [comment] 2021-04-24 04:29
oooohhhhhhhhh because we take one row off in pixel because of the bottom of the screen...but this isn't at the bottom of the screen...ahhh, yes.

**Comment by dankamongmen** [comment] 2021-04-24 04:33
no, that's just for scaled/stretched images, and we're `NCSCALE_NONE` here. the issue is with sixel clamping. we cut down to the next lowest multiple of 6; when we're less than 6 pixels, that means we become 0. let's confirm this:

* it ought work fine in kitty....**yes**
* it ought work fine at (6, 6), break at (5, 5), and work at (6, 1)...**yes**

ok, so that's it, 54534af1 broke this when we clamped down for sixels.

**Comment by dankamongmen** [comment] 2021-04-24 04:57
ok, so i think we can call this fixed based off the work earlier (regarding scaling after resizing), and the fact that this will work if you use a height of at least 6. i'm going to work on better sixel clamping, which will allow you to resize to the single pixel you crave, but that's another bug.

**Comment by joseluis** [comment] 2021-05-03 10:57
reopening this, the error was never fixed, and in 2.2.9 it segfaults as explained here https://github.com/dankamongmen/notcurses/pull/1609#issuecomment-830148314

**Comment by dankamongmen** [comment] 2021-05-05 02:17
Alright, digging into this tonight.

**Comment by dankamongmen** [comment] 2021-05-08 19:12
i'm reproducing this against 2.2.10:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/examples/issue-1559`
Error: NcError { int: -1, msg: "NcVisual.render()" }
```

**Comment by dankamongmen** [comment] 2021-05-08 19:19
i see this:

```rust
    let vframe = NcVisual::from_rgba(buffer.as_slice(), HEIGHT, WIDTH * 4, WIDTH)?;                                                                                                                                                                                                                                                                    
    let voptions =                                                                                                                                                                                                                                                                                                                                     
        NcVisualOptions::without_plane(0, 0, 0, 0, HEIGHT, WIDTH, NCBLIT_PIXEL, 0, 0);                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                       
    // vframe.inflate(1)?; // this works                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                       
    vframe.resize(6, 1)?;                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                       
    vframe.render(&mut nc, &voptions)?;          
```

and it makes me suspicious -- are you trying to render a 10x10 graphic  (based off the arguments to `without_plane()`) that you've just reduced to 6x1? that's not gonna work. let me investigate further, though.

**Comment by dankamongmen** [comment] 2021-05-08 19:26
the following translation of your code into c works just fine:

```c
#include <unistd.h>
#include <stdlib.h>
#include <notcurses/notcurses.h>

int main(void){
  struct notcurses_options opts = {
    .loglevel = NCLOGLEVEL_TRACE,
  };
  struct notcurses* nc = notcurses_init(&opts, NULL);
  if(notcurses_check_pixel_support(nc) != 1){
    notcurses_stop(nc);
    fprintf(stderr, "this program requires pixel support\n");
    return EXIT_FAILURE;
  }
  int HEIGHT = 100;
  int WIDTH = 100;
  uint32_t data[HEIGHT * WIDTH];
  for(size_t i = 0 ; i < HEIGHT * WIDTH ; ++i){
    data[i] = 0xffffffff;
  }
  struct ncvisual* ncv = ncvisual_from_rgba(data, HEIGHT, WIDTH * 4, WIDTH);
  if(ncv == NULL){
    notcurses_stop(nc);
    fprintf(stderr, "couldn't create ncvisual\n");
    return EXIT_FAILURE;
  }
  struct ncvisual_options vopts = {
    .blitter = NCBLIT_PIXEL,
  };
  struct ncplane* n;
  if((n = ncvisual_render(nc, ncv, &vopts)) == NULL){
    notcurses_stop(nc);
    fprintf(stderr, "couldn't render ncvisual\n");
    return EXIT_FAILURE;
  }
  notcurses_render(nc);
  sleep(3);
  ncplane_destroy(n);
  if(ncvisual_resize(ncv, 6, 1)){
    notcurses_stop(nc);
    fprintf(stderr, "couldn't resize ncvisual\n");
    return EXIT_FAILURE;
  }
  if((n = ncvisual_render(nc, ncv, &vopts)) == NULL){
    notcurses_stop(nc);
    fprintf(stderr, "couldn't render ncvisual\n");
    return EXIT_FAILURE;
  }
  notcurses_render(nc);
  sleep(3);
  ncvisual_destroy(ncv);
  notcurses_stop(nc);
  return EXIT_SUCCESS;
}
```

it first draws a 100x100 white square, then a 6x1 white line, in both kitty and xterm (redirect stderr).

if i change the `ncvisual_options` initialization to match what i think you're doing, however, it does indeed fail on the second render (as expected):

```
  struct ncvisual_options vopts = {                                             
    .leny = HEIGHT,                                                             
    .lenx = WIDTH,                                                              
    .blitter = NCBLIT_PIXEL,                                                    
  };        
```

and in the error output, i see:

```
init_lang:893:Set locale from LANG; client should call setlocale(2)!
get_tty_fd:488:Returning TTY fd 3
is_linux_console:548:Not a Linux console, KDGETMODE failed
ncplane_new_internal:452:Created new 70x80 plane "std" @ 0x0
ncplane_new_internal:452:Created new 5x10 plane "bmap" @ 0x0
ncplane_resize_internal:629:5x10 @ 0/0 → 5/10 @ 0/0 (keeping 5x10 from 0/0)
ncplane_resize_internal:629:70x80 @ 0/0 → 70/80 @ 0/0 (keeping 70x80 from 0/0)
ncplane_destroy:734:Destroying 5x10 plane "bmap" @ 0x0
[swscaler @ 0x55b1c89cd000] Forcing full internal H chroma due to odd output size
[swscaler @ 0x55b1c89cd000] Forcing full internal H chroma due to input having non subsampled chroma
ncvisual_blitset_geom:132:Geometry too large 100 > 6 or 100 > 1  <------------------------------------------------------

1 render, 144.96µs (144.96µs min, 144.96µs avg, 144.96µs max)
1 raster, 40.21µs (40.21µs min, 40.21µs avg, 40.21µs max)
1 write, 407.57µs (407.57µs min, 407.57µs avg, 407.57µs max)
52.25KiB (52.25KiB min, 52.25KiB avg, 52.25KiB max)
0 failed renders, 0 failed rasters, 0 refreshes
RGB emits:elides: def 0:0 fg 0:0 bg 0:0
Cell emits:elides: 0/11200 (100.00%) 0.00% 0.00% 0.00%
Sprixel emits:elides: 1/0 (0.00%)
couldn't render ncvisual
```

**Comment by dankamongmen** [comment] 2021-05-08 19:27
if i remove the `WIDTH` and `HEIGHT` from your code, and replace them with 0 (meaning "render everything available in this dimension"), the example works;

```
[schwarzgerat](0) $ git diff
diff --git rust/examples/issue-1559.rs rust/examples/issue-1559.rs
index 0e139130e..f12a8c0eb 100644
--- rust/examples/issue-1559.rs
+++ rust/examples/issue-1559.rs
@@ -23,7 +23,7 @@ fn main() -> NcResult<()> {
 
     let vframe = NcVisual::from_rgba(buffer.as_slice(), HEIGHT, WIDTH * 4, WIDTH)?;
     let voptions =
-        NcVisualOptions::without_plane(0, 0, 0, 0, HEIGHT, WIDTH, NCBLIT_PIXEL, 0, 0);
+        NcVisualOptions::without_plane(0, 0, 0, 0, 0, 0, NCBLIT_PIXEL, 0, 0);
 
     // vframe.inflate(1)?; // this works
 
[schwarzgerat](0) $
```

**Comment by dankamongmen** [comment] 2021-05-08 19:30
i've committed this change. from what i can tell, you need either {0, 0} there, or {6, 1} to match your actual resized image. it works with `ncvisual_inflate(1)` because `ncvisual_inflate()` takes a multiple, not a new size. providing it 1 means "keep the current size", which is {10, 10}, which works just fine for obvious reasons. if you wanted the `ncvisual_resize()` analogue, you'd want `ncvisual_resize(10, 10)`. perhaps that was the confusion?

**Comment by dankamongmen** [comment] 2021-05-08 19:31
i think this can be closed now. if i misunderstood something, don't hesitate to reopen.

**Closed by dankamongmen** 2021-05-08 19:31 UTC
Labels: bug, rust
