### ISSUE TITLE
ncplane_move_yx() on root planes operates relatively

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1753] opened 2021-06-11 09:21 UTC
So there's the function `ncplane_move_yx` that IIUC moves the plane a number of rows/cols relative to its current position. But there doesn't seem to be a function that moves to absolute coordinates (could be "absolute" in the context of the terminal dimensions, or its root plane)

This is different from the `ncplane_cursor_move_yx` function, which move the cursor to the absolute yx coordinates of the plane... 

Using the same function suffix for both is a tad confusing.

So I discovered today that my implementation of `ncplane_move_rel` was worse than redundant, since it was intended to do what `ncplane_move_yx` was already doing... by calling `ncplane_move_yx` as if it worked like `ncplane_cursor_move_yx`  (It seems I'm finding out lately a lot of misunderstundings like that).

Don't you think it would be useful to have a more absolute move function for planes? In any case I'll have to create something like that in the rust wrappers...

**Comment by joseluis** [comment] 2021-06-11 09:52
Ok, I think there's definitely something weird going on and I've created [this example](https://github.com/dankamongmen/notcurses/blob/c835941acd82d74f6ec9fd6d8f7fe675a80f7bb7/rust/examples/issue-1753.rs) to illustrate it:

It doesn't seem right that calling  `move_yx(1, 1)` on a plane from the standard pile moves it to the 1,1 coordinates of the standard plane... But calling  `move_yx(1, 1)` on a plane from a different pile moves it 1 col right and 1 row down...

**Comment by dankamongmen** [comment] 2021-06-11 18:29
> So there's the function ncplane_move_yx that IIUC moves the plane a number of rows/cols relative to its current position. But there doesn't seem to be a function that moves to absolute coordinates (could be "absolute" in the context of the terminal dimensions, or its root plane)

`ncplane_move_yx()` moves the plane to *absolute coordinates relative to the plane to which it is bound*, or at least should. it furthermore moves all planes (recursively) bound to it by the amount moved by the plane.

the whole point of binding planes is that they move with the parent. this is useful for building widgets etc., where you have multiple planes combining into one logical UI element. just move the root plane of the widget, and everything moves. this is how `ncreel`s for instance are implemented -- move the root reel, and all the tablets and any subplanes they have get moved. this is actually necessary for sane management, since users could be creating (bound) planes within the tablets, planes Notcurses wouldn't otherwise know to be related.

you say `ncplane_move_yx(1,1)` on an unbound plane moves it 1 right, 1 down; this should only be true when the plane starts off located at 0,0.

**Comment by dankamongmen** [comment] 2021-06-11 19:09
yep, will look into it ASAP

**Comment by dankamongmen** [comment] 2021-06-11 20:39
confirmed the behavior you're reporting. ok one mystery i can explain: in your standard plane example, you move to -1,-1 and you have a comment saying "relative?!" it's actually moving to -1,-1 if you put a screen ruler up on it, or use different characters. so it's an absolute move, just like the first one (in the standard plane). agreed that your other example (alternate pile) is behaving oddly. probably a bug of mine there.

**Comment by dankamongmen** [comment] 2021-06-11 20:40
ahhhhh yes i see the bug, i think.

**Comment by dankamongmen** [comment] 2021-06-11 20:41
yep. when i added piles, i didn't account for this in `ncplane_move_yx()`. good find!

**Comment by dankamongmen** [comment] 2021-06-11 20:47
```c
  if(n == ncplane_notcurses(n)->stdplane){                                                                 
    return -1;                                                                                             
  }                                                                                                        
  int dy, dx; // amount moved                                                                              
  dy = (n->boundto->absy + y) - n->absy;                                                                   
  dx = (n->boundto->absx + x) - n->absx;    
```

we throw out the standard plane with an error, good good. but other root planes are not thrown out, which is also correct. we then calculate `dy` and `dx`; since a root plane is bound to itself, the `absy`/`absx` terms cancel out, and `dy`/`dx` become purely relative.

**Comment by dankamongmen** [comment] 2021-06-11 20:51
fixed, unit test added, let me verify that your example runs as expected

**Comment by dankamongmen** [comment] 2021-06-11 20:52
good fix.

**Closed by dankamongmen** 2021-06-11 20:52 UTC
Labels: bug

**Comment by dankamongmen** [comment] 2021-06-11 20:54
i'm not sure how this affects your initial comments; if you still think we need new functionality, make a new issue on it. w00t!

**Comment by joseluis** [comment] 2021-06-11 21:08
works perfectly, thank you

I do think new functionality is handy, but I already added a function for relative movement in the rust bindings...

**Comment by dankamongmen** [comment] 2021-06-11 21:11
sure; i always figured it was trivial enough that, like, why bother. it would be done with the obvious implementation (`ncplane_move_yx(ncplane_yx() + args)`) as a static inline.

**Comment by joseluis** [comment] 2021-06-11 21:21
I see. In my case I'm trying to think in terms of having handy the most common needed functionality already assembled under a short identifier name in order to help reduce the cognitive weight, and the amount of code needed to write... It's not easy to make things simple...
