### ISSUE TITLE
cursor not being restored after ncdirect program runs

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#943] opened 2020-08-23 17:27 UTC
I just ran the `dirgb` PoC, and didn't have a cursor visible when it exited. Everything else seemed to work fine. When did this start? I'm pretty sure this didn't use to be the case.

**Comment by dankamongmen** [comment] 2020-08-23 17:29
actually, hrm, it was *visible*, just...not very bright? and once it came off of the output we'd generated, it went back to white. interesting. probably not a problem.

**Comment by joseluis** [comment] 2020-08-23 17:30
That works well for me, ofc if you disable the cursor an exit then yes...

**Comment by joseluis** [comment] 2020-08-23 17:32
But... Italic doesn't seem to work for me anymore ...

**Comment by dankamongmen** [comment] 2020-08-23 17:36
if you disable the cursor and call `ncdirect_stop()`, it still ought enable the cursor. whether this is desirable is questionable, but notcurses in full or direct mode is always supposed to leave you with:

 * palette reset (`oc` terminfo)
 * cursor visible (`cnorm` terminfo)
 * all styles reset (`sgr0` terminfo)

anyway, it looks like this was a false alarm. the cursor takes as its color of the cell's foreground color. if you exit and the cursor is atop colored text, it'll be colored there. once you leave the area, it's fine. this isn't a bug.

![2020-08-23-133615_722x857_scrot](https://user-images.githubusercontent.com/143473/90984821-a57a9600-e545-11ea-95a0-f5d956f6f2f9.png)

**Comment by joseluis** [comment] 2020-08-23 19:20
> notcurses in full or direct mode is always supposed to leave you with:

Thank you, I've put that as a comment in the rust bindings when calling *_stop

**Comment by joseluis** [comment] 2020-08-23 21:32
> if you disable the cursor and call `ncdirect_stop()`, it still ought enable the cursor.

Reopening because it doesn't work for me...

```rust
use core::ptr::null;
use libnotcurses_sys as nc;

extern "C" {
    fn libc_stdout() -> *mut nc::_IO_FILE;
}

fn main() {
    unsafe {
        let ncd = nc::ncdirect_init(null(), libc_stdout());
        nc::ncdirect_cursor_disable(ncd);
        nc::ncdirect_stop(ncd);
    }
}
```

This leaves me without cursor after program runs. I can restore it opening vim and coming back, for example....

**Comment by joseluis** [comment] 2020-08-23 21:35
It does seem to work with full mode, though...

**Comment by dankamongmen** [comment] 2020-08-25 09:03
Hrmmm. I took the source you posted above, and ran `cargo new direct --bin`. Running it with `cargo run`, I always get my cursor back. I'm running xfce4-terminal for this experiment. I also retain my cursor if I run the binary `target/debug/direct`:

```
[schwarzgerat](0) $ cargo build
   Compiling dir v0.1.0 (/home/dank/src/dankamongmen/notcurses/dir)
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
[schwarzgerat](0) $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/dir`
Hello, world!
[schwarzgerat](0) $ 
[schwarzgerat](0) $ 
[schwarzgerat](0) $ ls
Cargo.lock  Cargo.toml  dir  src  target
[schwarzgerat](0) $ target/debug/dir
Hello, world!
[schwarzgerat](0) $ 
```

![2020-08-25-050122_722x857_scrot](https://user-images.githubusercontent.com/143473/91154940-26de3f80-e690-11ea-8ee8-3387579766ed.png)

let me play around with it for a minute, but I'm not sure I can reproduce this. if i can't, i'd be appreciative of an `strace` run, maybe with `-s 1024` or something. i'd like to know exactly what we're writing.

**Comment by dankamongmen** [comment] 2020-08-25 09:07
Ignore my last (deleted) comment. I am dumb.

Using your actual program, I'm not able to reproduce cursor loss. Here's what we're writing, according to `strace`:

```

write(1, "\33[?1h\33=\33[0m\17\33[?25l", 18) = 18
write(1, "\33[39;49m", 8)               = 8
write(1, "\33[0m\17", 5)                = 5
write(1, "\33]104\7", 6)                = 6
write(3, "\33[?25h", 6)                 = 6
```

**Comment by dankamongmen** [comment] 2020-08-25 09:08
```
[schwarzgerat](0) $ infocmp -a | grep cnorm
	clear=\E[H\E[2J, cnorm=\E[?25h, cr=\r,
[schwarzgerat](0) $ 
```

so that last one is definitely `cnorm`, and ought be bringing our cursor back.

```
[schwarzgerat](0) $ infocmp -a | grep civis
	bel=^G, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
[schwarzgerat](0) $ 
```

there's civis, which is indeed being written in the first `write()`...

**Comment by dankamongmen** [comment] 2020-08-25 09:10
I'll kick this back to you. I can't seem to reproduce over a few dozen tries.

**Comment by joseluis** [comment] 2020-08-25 19:22
Sorry this week I'm busier...

It turns out I also can't reproduce it anymore, that was a surprise! I don' know what happened there. Oh well.... closing!

**Closed by joseluis** 2020-08-25 19:22 UTC
Labels: bug

**Comment by dankamongmen** [comment] 2020-08-25 20:52
Thanks for verifying! Didn't mean to come across as impatient/demanding, just indicating that I was no longer actively working on investigation =]. Sweet.

**Comment by joseluis** [comment] 2020-08-25 22:16
Don't worry I understood you well. I was more worried about wasting your time. Also I don't like not understanding what happened with the bug, but I'm glad it's no more.

This week I have noiciable less time for working on this, but I'm still eager to continue as soon as I can.

cheers!
