### ISSUE TITLE
error when printing sixels in direct mode in xterm

### ISSUE THREAD

**Issue by db48x** [dankamongmen/notcurses#1716] opened 2021-06-03 12:15 UTC
But Alacritty and Kitty work fine. Xterm (which is running in VT340 mode) just prints “Won't create denormalized plane (r=0, c=35)” instead of my image.

I took a recording using rr, and put a breakpoint on line 374 of notcurses.c in the function `ncplane_new_internal`. I went up to the parent frame and printed out `n`, and saw this:

    sixel_maxx = 4096,
    sixel_maxy = 0,

The image I’m passing in is definitely more than zero pixels tall, so I set a watchpoint on `*(int*)n->tcache.sixel_maxy` and ran the program in reverse (using the `reverse-continue` command). It hit the watchpoint at line 408 of termdesc.c in `read_xtsmgraphics_reply`.

I checked what Xterm is actually replying with:

```
 read -p $'\e[?2;4;0S' -rsdS; printf "%q\n" $REPLY
$'\E[?2;3;0;0'
```

If I’m reading the documentation correctly, that 3 indicates a failure. Is that right?

So I think notcurses needs to better handle errors here, with some reasonable fallback.

Also, itș weird that read_xtsmgraphics_reply returns one value and has an out param for the other. Also, that it sets the out param to 0 when it finds the fourth parameter.

Here’s the (Rust) code that I’m using to output the image:
```rust
use libnotcurses_sys::*;
let mut nc = NcDirect::new().expect("couldn’t create ncdirect");
nc.check_pixel_support().expect("failed to check for sixel support");
let vframe1 = NcVisual::from_bgra(dt.get_data_u8(), img_dim.1 as u32, (img_dim.0 * 4) as u32, img_dim.0 as u32).expect("couldn’t create visual");
let voptions = NcVisualOptions::fullsize_pixel_without_plane(0, 0, img_dim.1 as u32, img_dim.0 as u32);
unsafe {
    let v = ffi::ncdirectf_render(nc, vframe1, NCBLIT_PIXEL, NCSCALE_NONE, 0, 0);
    if !v.is_null() {
        ncdirect_raster_frame(nc, v, NCALIGN_LEFT);
    }
}
vframe1.destroy();
nc.stop().expect("failed to destroy ncdirect context");
```

Have I missed anything?

**Comment by dankamongmen** [comment] 2021-06-03 13:20
on it! btw, i was blown away by the work you posted on http://db48x.net/reposurgeon/repl-demo-4/, and want to do everything in my power to facilitate this kind of thing. don't hesitate to ask for features and such.

**Comment by db48x** [comment] 2021-06-03 14:17
> on it! btw, i was blown away by the work you posted on http://db48x.net/reposurgeon/repl-demo-4/

Thanks!

> don't hesitate to ask for features and such.

I’ll probably think of something :)

**Comment by dankamongmen** [comment] 2021-06-09 10:17
is it possible that this was fixed by work in #1725/#1730? i'll run your rust code and see if the problem is still happening.

**Comment by dankamongmen** [comment] 2021-06-09 10:21
i'm getting all manner of errors compiling the rust code you provided; let me try and cons up some equivalent c and see what's going on

**Comment by dankamongmen** [comment] 2021-06-09 10:26
i don't see where the `voptions` struct you're creating is being used in your example code, nor indeed how it would possibly be used before #1742 is merged. hrmm.

**Comment by dankamongmen** [comment] 2021-06-09 10:31
the following c code, which i believe equivalent to your rust, works as expected in Xterm:

```
[grimes](130) $ ./db 
 [grimes](0) $ cat ../src/poc/db.c 
#include <notcurses/direct.h>
#include <notcurses/notcurses.h>

int main(void){
  struct ncdirect* nc = ncdirect_init(NULL, NULL, 0);
  if(nc == NULL){
    return EXIT_FAILURE;
  }
  if(ncdirect_check_pixel_support(nc) < 1){
    goto err;
  }
  uint32_t data[] = { 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, };
  struct ncvisual* ncv = ncvisual_from_bgra(data, 1, 16, 4);
  if(ncv == NULL){
    goto err;
  }
  ncdirectv* nv = ncdirectf_render(nc, ncv, NCBLIT_PIXEL, NCSCALE_NONE, 0, 0);
  if(nv == NULL){
    goto err;
  }
  if(ncdirect_raster_frame(nc, nv, NCALIGN_LEFT)){
    goto err;
  }
  if(ncdirect_stop(nc)){
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;

err:
  ncdirect_stop(nc);
  return EXIT_FAILURE;
}
[grimes](0) $ 
```

let me consult your original report and see whether there's something i'm missing here

**Comment by dankamongmen** [comment] 2021-06-09 10:35
whoa, it had `sixel_maxy = 0`?!? ok that's our problem. why on earth is it getting `sixel_maxy=0`?

that's not a property of your image; that's a property of the system support, as returned when queried with `XTSMGRAPHICS`.

what does `caps-rendered` show when you run it in this environment? i get in a sample xterm:

```
[grimes](0) $ ./caps-rendered 
 notcurses 2.3.2 by nick black et al on xterm-256color
  24 rows (24px) 80 cols (12px) (30.00KiB) 48B crend 256 colors+RGB
  compiled with gcc-11.1.0, 16B little-endian cells
  terminfo from ncurses 6.2.20200212
  avformat 58.76.100 avutil 56.70.100 swscale 5.9.100
 Colors: 256 rgb: y ccc: y setaf: y setab: y
 sgr: y sgr0: y op: y fgop: y bgop: y
 rows: 24 cols: 80 rpx: 24 cpx: 12 (576x960)
 max sixel size: 1440x1980 colorregs: 256        <=--------------------------------------------------------
 UTF8: y quad: n sex: n braille: y images: y videos: y
    Quads { ▘▝▀▖▌▞▛▗▚▐▜▄▙▟█}
 Sextants ⎧ 🬀🬁🬂🬃🬄🬅🬆🬇🬈🬊🬋🬌🬍🬎🬏🬐🬑🬒🬓▌🬔🬕🬖🬗🬘🬙🬚🬛🬜🬝⎫
          ⎩🬟🬠🬡🬢🬣🬤🬥🬦🬧▐🬨🬩🬪🬫🬬🬭🬮🬯🬰🬱🬲🬳🬴🬵🬶🬷🬸🬹🬺🬻█⎭
  Braille {⠀⢀⢠⢰⢸⡀⣀⣠⣰⣸⡄⣄⣤⣴⣼⡆⣆⣦⣶⣾⡇⣇⣧⣷⣿}
 Lower ⅛s { ▁▂▃▄▅▆▇█}
 background isn't interpreted as transparent
 cup: y vpa: y hpa: y
[grimes](0) $ 
```

so i'm supporting sixels of up to 1980x1440 in this XTerm. does yours show `0x4096`?

if so, what's the value of your `maxGraphicSize` XResource? in my `.Xresources`, I have:

```
XTerm*maxGraphicSize: 1980x1440
```

which leads to the 1980x1440 support we see here. @db48x , let me know, thanks!

**Comment by db48x** [comment] 2021-06-09 13:35
Here’s what I get:

![Screenshot from 2021-06-09 06-32-22](https://user-images.githubusercontent.com/228849/121364465-56142380-c927-11eb-89fb-781a1774d867.png)

**Comment by dankamongmen** [comment] 2021-06-09 17:37
so that "didn't detect bitmap graphics support" is a big problem, and that's why you're getting the 0. i'm surprised it's allowing you to then go on and use `NCBLIT_PIXEL`, if that's indeed what's getting chosen (you would need `NCVISUAL_OPTION_NODEGRADE` to ensure it, but in the config you show above, it ought be rejected).

also, wow your font is missing an absolute ton of glyphs.

you've clearly got `TERM=xterm-256color`. is this actually xterm? what are the following two XResources set for you?

```
XTerm*decGraphicsID: 340
XTerm*decTerminalID: 420
```

here is my guess as to what's happening:

* your XTerm is not configured to respond as supporting Sixel (hence "didn't detect bitmap support")
  * i suspect that `ncdirect_check_pixel_support()` is returning -1 or 0, most likely 0. success is 1. rust wrapper might need a fix here
* you're using `NCBLIT_PIXEL` without `NODEGRADE`. so we hit `lookup_blitset` and run into:

```c
  // without bitmap support, NCBLIT_PIXEL decays to NCBLIT_3x2                                             
  if(!tcache->bitmap_supported && setid == NCBLIT_PIXEL){                                                  
    if(may_degrade){                                                                                       
      setid = NCBLIT_3x2;                                                                                  
    }else{                                                                                                 
      return NULL;                                                                                         
    }                                                                                                      
  }                 
```

you likewise don't have quads or sextants, so this is going to drop all the way to `NCBLIT_2x1` aka halfblocks. i strongly suspect that your output there is all of the form ▀ U+2580 UPPER HALF BLOCK

* XTerm is giving you different results because in the other terminals you're successfully using `NCBLIT_PIXEL`, and this is giving you some wildly different geometry for the same image (i want to track this down and ensure there's not a bug here)

so my thoughts are:

* if default XTerm doesn't indicate sixel support, that sucks, and we'll need to document the XResources (fat help that will be)
* if you ensure you are advertising sixel support, i bet things will work
* we ought make sure rust is only considering a positive result from `*_check_sixel_support()` as success
* if you only want pixel, you need use `NCVISUAL_OPTION_NODEGRADE` to inhibit blitter fallback
* i still want to look into the error you're seeing about plane creation, and ensure that's not a bug

this is kinda depressing. most people don't even know how to update their X resource database. this will be hellish to support. and maybe degrade-by-default wasn't a great design choice.

thanks for sticking with it; let me know if any of this pans out, thanks!

**Comment by dankamongmen** [comment] 2021-06-09 19:21
ahhh! you only have 16 color registers! ok i'm not sure how that's leading me to think you don't support sixel at all, but that definitely would be the end result. from `sixel.c`:

```c
  // FIXME enforce this in discovery, possibly raising the value                                           
  if(colorregs < 64){                                                                                      
    return -1;                                                                                             
  }                 
```

if you add

`XTerm*numColorRegisters: 256`

to your X Resources, do you get different behavior? and i'm going to simulate the 16 case right now and get rid of this FIXME

**Comment by dankamongmen** [comment] 2021-06-09 19:21
hrmm that's not it

` max sixel size: 1440x1980 colorregs: 16`

**Comment by dankamongmen** [comment] 2021-06-09 19:26
reproduced by downgrading my terminal from 420 to 340:

```
[schwarzgerat](0) $ read -p $'\e[?1;1;0S\e[c' -rsdc; printf "%q\n" $REPLY
$'\E[?1;0;16S\E[?63;1;2;4;6;9;15;16;22;28'
[schwarzgerat](0) $ ./caps-rendered 

 notcurses 2.3.2 by nick black et al on xterm-256color
  24 rows (23px) 80 cols (11px) (30.00KiB) 48B crend 256 colors+RGB
  compiled with gcc-10.2.1 20210110, 16B little-endian cells
  terminfo from ncurses 6.2.20201114
  avformat 58.79.100 avutil 56.74.100 swscale 5.10.100
 Colors: 256 rgb: y ccc: y setaf: y setab: y
 sgr: y sgr0: y op: y fgop: y bgop: y
 rows: 24 cols: 80 rpx: 23 cpx: 11 (552x880)
 didn't detect bitmap graphics support
 UTF8: y quad: n sex: n braille: y images: y videos: y
    Quads { ▘▝▀▖▌▞▛▗▚▐▜▄▙▟█}
 Sextants ⎧ 🬀🬁🬂🬃🬄🬅🬆🬇🬈🬊🬋🬌🬍🬎🬏🬐🬑🬒🬓▌🬔🬕🬖🬗🬘🬙🬚🬛🬜🬝⎫
          ⎩🬟🬠🬡🬢🬣🬤🬥🬦🬧▐🬨🬩🬪🬫🬬🬭🬮🬯🬰🬱🬲🬳🬴🬵🬶🬷🬸🬹🬺🬻█⎭
  Braille {⠀⢀⢠⢰⢸⡀⣀⣠⣰⣸⡄⣄⣤⣴⣼⡆⣆⣦⣶⣾⡇⣇⣧⣷⣿}
 Lower ⅛s { ▁▂▃▄▅▆▇█}
 background isn't interpreted as transparent
 cup: y vpa: y hpa: y
[schwarzgerat](0) $ 
```

tally-ho!

**Comment by dankamongmen** [comment] 2021-06-09 19:26
almost certainly a stupid error in `query_sixel()`, which is going away anyway, but let's get this fixed up for our good man mr. brooks

**Comment by dankamongmen** [comment] 2021-06-09 19:31
no, that was just due to leaving color registers at 16 after making that fix. 340 with 64/256 cregs gets picked up fine. what the hell?

**Comment by dankamongmen** [comment] 2021-06-09 19:34
hrmmmmmmm.

```
[schwarzgerat](0) $ read -p $'\e[?2;4;0S\e[?1;1;0S\e[c' -rsdc; printf "%q\n" $REPLY
$'\E[?2;0;1980;1440S\E[?1;0;256S\E[?64;1;2;4;6;9;15;16;17;18;21;22;28'
[schwarzgerat](0) $ 
```

what do you get from 2;4;0 (command provided above)?

**Comment by db48x** [comment] 2021-06-09 19:38
vt420 doesn’t have sixel support :)

for 2;4;0 I get this, in vt340 mode:

```
 read -p $'\e[?2;4;0S\e[c' -rsdc; printf "%q\n" $REPLY
$'\E[?2;3;0;0S\E[?63;1;2;4;6;9;15;22'
```

in vt420 mode:

```
 read -p $'\e[?2;4;0S\e[c' -rsdc; printf "%q\n" $REPLY
$'\E[?2;3;0;0S\E[?64;1;2;6;9;15;18;21;22'
```

**Comment by dankamongmen** [comment] 2021-06-09 19:40
bah! i screwed this all up. 4 requests the maximum possible value. i want Pi=1 here, argh

**Comment by dankamongmen** [comment] 2021-06-09 19:41
one more, please:

```
[schwarzgerat](0) $ read -p $'\e[?2;1;0S\e[?1;1;0S\e[c' -rsdc; printf "%q\n" $REPLY
$'\E[?2;0;880;552S\E[?1;0;256S\E[?64;1;2;4;6;9;15;16;17;18;21;22;28'
[schwarzgerat](0) $ 
```

**Comment by db48x** [comment] 2021-06-09 19:51
That gets me 1000×1000 in both:

```
 read -p $'\e[?2;1;0S\e[c' -rsdc; printf "%q\n" $REPLY
$'\E[?2;0;1000;1000S\E[?63;1;2;4;6;9;15;22'
```

**Comment by db48x** [comment] 2021-06-09 19:53
Hrm. It still doesn’t detect sixel support after that change…

**Comment by dankamongmen** [comment] 2021-06-09 19:53
yay, i expect that with 761ab46 you will see different behavior, if you take the number of color registers up to at least 64 (i recommend 256). this can be achieved with:

`XTerm*numColorRegisters: N` (N>=64)

notcurses will not currently make use of more than 256 color registers, even if they are available.

i have an open bug on taking up the number of supported registers automatically, but it's not there yet

**Comment by dankamongmen** [comment] 2021-06-09 19:54
assuming the color register change gets things working for you, i will prioritize #1528, which i can probably have done tonight.

**Comment by db48x** [comment] 2021-06-09 19:56
Ok, after bumping the color registers up it now works: 

```
max sixel size: 1000x1000 colorregs: 1024
```

**Comment by db48x** [comment] 2021-06-09 19:57
Hah, except that my reposurgeon prototype segfaults!

**Comment by dankamongmen** [comment] 2021-06-09 20:01
> Ok, after bumping the color registers up it now works:
> ```
> max sixel size: 1000x1000 colorregs: 1024
> ```

woooohooo your patience and competence as an early adopter is a great gift

i will prioritize #1528 and try to knock out #1692 at the same time. that might well qualify us for a 2.3.3.

i assume you were not seeing segfaults on kitty etc with the same code? a new adventure! if you want to paste the exactish rust, i'll debug it for you and ensure it's not my bug or @joseluis 's; you've already given us a lot of your time. just let me know how i can best help you next. i'm gonna close this one up. **THANK YOU**.

**Closed by dankamongmen** 2021-06-09 20:01 UTC
Labels: bitmaps, bug

**Comment by db48x** [comment] 2021-06-09 20:06
I figure it out; someone changed the function signature for NcDirectF::ncdirectf_render, which mean that the compiled binary was passing in a `0` instead of a proper `&NcVisualOptions`. When I recompiled it the typechecker complained, of course. While technically that kind of breaking change shouldn’t be done in a minor release, I don’t think you should undo it.

**Comment by dankamongmen** [comment] 2021-06-10 01:52
hah, was wondering if it might be exactly that. yep, that was me last night; it was definitely the right thing for the future, but as `NOTE`d:

>   * `ncdirect_renderf()` has been changed to accept a `ncvisual_options`, replacing and extending its four final arguments. Sorry about the breakage here, but `ncdirect_renderf()` was introduced pretty recently (2.3.1). As a result, `ncdirect_renderf()` and `ncdirect_stream()` now honor `NCVISUAL_OPTION_BLEND` and `NCVISUAL_OPTION_NOINTERPOLATE`. All of this also applies to `ncdirect_geomf()`.

except the last line refers to the future, like tomorrow or so; see #1746, and the PR going up literally right now for it

**Comment by joseluis** [comment] 2021-06-13 10:41
> > * `ncdirect_renderf()` has been changed to accept a `ncvisual_options`, replacing and extending its four final arguments. Sorry about the breakage here, but `ncdirect_renderf()` was introduced pretty recently (2.3.1). As a result, `ncdirect_renderf()` and `ncdirect_stream()` now honor `NCVISUAL_OPTION_BLEND` and `NCVISUAL_OPTION_NOINTERPOLATE`. All of this also applies to `ncdirect_geomf()`.

```sed
s/ncdirect_renderf/ncdirectf_render/g
```

**Comment by dankamongmen** [comment] 2021-06-13 14:13
> > > * `ncdirect_renderf()` has been changed to accept a `ncvisual_options`, replacing and extending its four final arguments. Sorry about the breakage here, but `ncdirect_renderf()` was introduced pretty recently (2.3.1). As a result, `ncdirect_renderf()` and `ncdirect_stream()` now honor `NCVISUAL_OPTION_BLEND` and `NCVISUAL_OPTION_NOINTERPOLATE`. All of this also applies to `ncdirect_geomf()`.
> 
> ```sed
> s/ncdirect_renderf/ncdirectf_render/g
> ```

thanks, fixed in NEWS and on the release page
