### ISSUE TITLE
start running windows github actions

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1922] opened 2021-07-12 19:00 UTC
@igo95862 , @michaelsbradleyjr , i think this was probably in the various discussions, but:

* i'm seeing a windows workflow in `.github/workflows`, and
* https://dvdhrm.github.io/2021/04/21/meson-msvc-github-actions/ suggests i ought be able to build on windows at github's expense (and prepared infrastructure), yet
* our windows build doesn't appear to be running

what need i do to turn it on? i'm hoping to have windows and mac turned up soon.

this is a prerequisite for #463

**Comment by michaelsbradleyjr** [comment] 2021-07-12 19:08
I believe it's because the GHA workflows for Windows and macOS depend on 3rd party actions. The settings for this repository would need to be changed to allow 3rd party actions to run as part of a workflow.

These are the 3rd party actions related to Windows:

(maintained by the same people who maintain MSYS2)
https://github.com/dankamongmen/notcurses/blob/master/.github/workflows/windows_test.yml#L17

(maintained by GitHub employees)
https://github.com/dankamongmen/notcurses/blob/master/.github/workflows/windows_test.yml#L34

And this is the one related to macOS:

(maintained by GitHub employees)
https://github.com/dankamongmen/notcurses/blob/master/.github/workflows/macos_test.yml#L28

**Comment by dankamongmen** [comment] 2021-07-12 20:04
sweet, let me go see what i can do, thanks man!

**Comment by dankamongmen** [comment] 2021-07-12 20:05
i changed "allow local actions only" to "allow all actions". let's see what happens!

**Comment by michaelsbradleyjr** [comment] 2021-07-12 20:40
They can be run now, but still need to be triggered manually, from the Actions menu.

**Comment by michaelsbradleyjr** [comment] 2021-07-14 16:21
I can remove the necessity for the Windows build to be manually triggered, if that is desirable.

**Comment by WSLUser** [comment] 2021-07-16 15:21
I would keep it as manual until Windows works as intended. MacOS may be able to part of the automated CI now though.

**Comment by michaelsbradleyjr** [comment] 2021-07-21 15:24
Closed by #1953.

**Closed by michaelsbradleyjr** 2021-07-21 15:24 UTC
Labels: enhancement, mswindows
