### ISSUE TITLE
split multimedia components into separate library

### ISSUE THREAD

**Issue by kaniini** [dankamongmen/notcurses#1224] opened 2020-12-17 12:09 UTC
I am looking into building some programs with notcurses as a possible replacement to the current Alpine setup scripts.

Notcurses looks like it solves my gripes with ncurses, but having the multimedia components inside libnotcurses is a real bummer -- it adds ffmpeg and OpenImageIO to the dependency path of software which just wants to display some basic TUI widgets and so on.

Splitting out the multimedia components would allow programs that need just basic functionality to not also inherit the weight of ffmpeg and other media libraries, which would be hard to justify mastering onto an ISO just for the installer.

**Comment by dankamongmen** [comment] 2020-12-17 20:05
Completely agreed -- I was thinking about just this yesterday after you mentioned you were building an installer around it. This issue is a duplicate of #339, which I will promote in importance. Closing as duplicate.

**Closed by dankamongmen** 2020-12-17 20:05 UTC
Labels: documentation, duplicate, enhancement

**Comment by dankamongmen** [comment] 2020-12-17 20:07
@kaniini , I'm going to think about the best way to handle this, put my thoughts down in #339, and ideally move forward with this by EoY 2020 (2.2.x cycle).

In the meantime, know that you can build notcurses with `USE_MULTIMEDIA=none` and leave out ffmpeg/oiio.
