### ISSUE TITLE
A mouse click can select a disabled item

### ISSUE THREAD

**Issue by kascote** [dankamongmen/notcurses#2582] opened 2022-01-29 00:44 UTC
After a mouse click and using `ncmenu_mouse_selected`, it returns the menu name without take into account the disabled state

Please include the following data:
* COLORTERM=24bit
LANG=en_US.UTF-8
LESS_TERMCAP_mb=$'\C-[[01;31m'
LESS_TERMCAP_md=$'\C-[[01;38;5;74m'
LESS_TERMCAP_me=$'\C-[[0m'
LESS_TERMCAP_se=$'\C-[[0m'
LESS_TERMCAP_so=$'\C-[[38;5;246m'
LESS_TERMCAP_ue=$'\C-[[0m'
LESS_TERMCAP_us=$'\C-[[04;38;5;146m'
TERM=xterm-kitty
TERMINFO=/Applications/kitty.app/Contents/Resources/kitty/terminfo
* notcurses version 3.0.5
* terminal Kitty 0.24.1

**Comment by dankamongmen** [comment] 2022-01-29 17:39
great find, thanks a lot for the report! i'll try to fix this up today for 3.0.6; it'll definitely be fixed by 3.1.0.

**Comment by dankamongmen** [comment] 2022-02-01 23:28
alright, i'm looking into this using the `menu` PoC, and i'm unable to select any actual menu items with the mouse...hrm (xterm or kitty)

**Comment by dankamongmen** [comment] 2022-02-01 23:29
i *can* select a top-level menu with the mouse, and it correctly does not select a disabled one...hrmm

**Comment by dankamongmen** [comment] 2022-02-01 23:30
meanwhile, `notcurses-demo` seems to have no mouse capability....what the hell's going on?

**Comment by kascote** [comment] 2022-02-01 23:39
the item is not selected, but the 'click' event came back from the `get` method, if you send the key event throw `ncmenu_mouse_selected` will return the item at that position, if the item is disabled must return null

**Comment by dankamongmen** [comment] 2022-02-01 23:40
ok, i've got `notcurses-demo` fixed up for mouse menu events in master; we were throwing away any `NCKEY_RELEASE`. now let's see what elese is going on here.

**Comment by kascote** [comment] 2022-02-01 23:40
for me this is not time sensitive or nothing.. prioritize as you will...

**Comment by dankamongmen** [comment] 2022-02-01 23:41
nah, i'm looking into it now =] sorry it took even this long

**Comment by dankamongmen** [comment] 2022-02-01 23:43
so it would seem that fixed `notcurses-demo` only for the `notcurses-demo` menu, not the `help` menu. so i suspect we have coordinate translation problems in play here, as well. probably need do a long hard look at how `ncmenu` handles mouse events, as i wrote this code back in the pre-1.0 days, and a great deal has changed since then.

**Comment by dankamongmen** [comment] 2022-02-07 13:10
ok, looking at `menu.c`, we don't seem to handle subsection events there, just toplevel. That surprises me.

In that case, everyone must be supplying their own subsection handler...which yeah, makes sense, since it needs to run in our input context....right? Let's verify that...indeed, that's the whole point of `ncmenu_mouse_selected()`.

ok, let me add that handler to the menu PoC, first off. it's already in `notcurses-demo`.

**Comment by dankamongmen** [comment] 2022-02-07 13:12
i think we might possibly have introduced a regression when we moved to pixel-based mouseclicks? i've added it to `menu`, and successfully picked up `Quit` sometimes:

```
Y/X: 6/19
WIN Y/X: 6/19 dimy: 8
SELECTION: Quit
```

but other clicks that seemed to be there did not:

```
Y/X: 0/19
WIN Y/X: 0/19 dimy: 8
SECTION_X: 1
Y/X: 6/20
WIN Y/X: 6/20 dimy: 8
SELECTION: (null)
Y/X: 5/21
WIN Y/X: 5/21 dimy: 8
SELECTION: (null)
Y/X: 4/22
```

**Comment by dankamongmen** [comment] 2022-02-07 13:20
ok so two problems noticed while adding this to `menu`:

* bottom menu clicks are off by one line
* clicks are only working through the text of the label, not through the breadth of the menu

**Comment by dankamongmen** [comment] 2022-02-07 13:44
heh see #2606, ugh

**Comment by dankamongmen** [comment] 2022-02-07 13:45
ok the `menu` PoC now supports mouse events for menu items; i'm going to resolve the problems listed above

**Comment by dankamongmen** [comment] 2022-02-07 13:47
menus should open to the first non-disabled item, also. if you disable the first item, it's still selected upon first opening.

**Comment by dankamongmen** [comment] 2022-02-07 14:01
> menus should open to the first non-disabled item, also. if you disable the first item, it's still selected upon first opening.

this is done

**Comment by dankamongmen** [comment] 2022-02-07 14:25
we ought just be able to use these, no?

```c
  int xoff;               // column offset from beginning of menu bar                                                               
  int bodycols;           // column width of longest item    
```

**Comment by dankamongmen** [comment] 2022-02-07 14:33
alright, we now accept ncmenu mouse clicks through the proper horizontal range

**Comment by dankamongmen** [comment] 2022-02-07 14:35
alright, we now pick up the correct item for mouseclicks on bottom menus

**Comment by dankamongmen** [comment] 2022-02-07 14:50
ok, all this crap seems to work now.

**Closed by dankamongmen** 2022-02-07 14:50 UTC
Labels: bug
