### ISSUE TITLE
Notcurses not compiling due to 'WA_ITALIC' being undeclared

### ISSUE THREAD

**Issue by ask6155** [dankamongmen/notcurses#1077] opened 2020-10-21 14:35 UTC
Notcurses it not able to find some things I guess. This error happens when I manually build it and even when I build the AUR version. Maybe it is because I messed up ncurses or something since I saw it was a dependency.

Anyway here's the log:
https://bin.snopyta.org/?3ffeb5dc68da15cd#7P2sBpG3a9vAV8zvM4VaWWqkdV1gmyvsF7dr1ZFoYRY7

In this build log I disabled qrencode, doctest, pandoc,
The AUR one has everything enable and it still fails

Plz help

**Comment by dankamongmen** [comment] 2020-10-21 16:46
Hrmmmmm so everything it's missing here is stuff coming from NCURSES (or more correctly, the terminfo library shipped with NCURSES). The Arch `PKGBUILD` lists ncurses as a hard dependency:

```
arch=('x86_64')
# qrcodegen is currently shipped as a static archive on Arch, rather than a
# dynamic library. Should the .so be shipped in the future, promote qrcodegen
# from a makedepends to a true depends, and use that dynamic library.
depends=('ncurses' 'ffmpeg' 'libunistring')
makedepends=('cmake' 'pandoc' 'python-pypandoc' 'python-cffi' 'python-setuptools' 'doctest' 'qrcodegen' 'ninja')
source=("https://github.com/dankamongmen/notcurses/archive/v${pkgver}.tar.gz")
```

and CMake also checks for it...

```
# some distros (<cough>motherfucking alpine</cough> subsume terminfo directly
# into ncurses. accept either, and may god have mercy on our souls.
pkg_search_module(TERMINFO REQUIRED tinfo>=6.1 ncursesw>=6.1)
set_property(GLOBAL APPEND PROPERTY PACKAGES_FOUND terminfo)
set_package_properties(terminfo PROPERTIES TYPE REQUIRED)
```

are you building from a source checkout, or via Arch's AUR?

**Comment by dankamongmen** [comment] 2020-10-22 07:19
This definitely looks like some kind of horribly broken ncurses installation. On my Arch laptop, I have `WA_ITALIC` defined in `/usr/include/curses.h`. Can you verify that this file is present, and contains this definition, on your install?

```
[grimes](0) $ grep -r WA_ITALIC /usr/include/
/usr/include/curses.h:#define WA_ITALIC	A_ITALIC	/* ncurses extension */
[grimes](0) $ 
```

**Comment by dankamongmen** [comment] 2020-10-22 07:20
Your buildlog also complains about being unable to find `curses_version()`. This ought be in the same place:

```
[grimes](0) $ grep -r curses_version /usr/include/
/usr/include/curses.h:extern NCURSES_EXPORT(const char *) curses_version (void);
/usr/include/curses.h:#define curses_version() NCURSES_VERSION
[grimes](0) $ 
```

**Comment by ask6155** [comment] 2020-10-22 10:49
well I tried both the greps and they both worked and found the declarations

**Comment by dankamongmen** [comment] 2020-10-23 08:35
Hrmmm.  So another weird thing is that there are other declarations in these files which we use, and which we seem to be finding without a problem. Like, around `WA_ITALIC`, we have this:

```
    if(nocolor_stylemask & WA_BLINK){
      ti->blink = NULL;
    }
    if(nocolor_stylemask & WA_DIM){
      ti->dim = NULL;
    }
    if(nocolor_stylemask & WA_BOLD){
      ti->bold = NULL;
    }
    if(nocolor_stylemask & WA_ITALIC){
      ti->italics = NULL;
    }
  }
```

and those are all succeeding without a problem. And when we go look at `curses.h`, we have:

```
#define WA_REVERSE  A_REVERSE
#define WA_BLINK  A_BLINK
#define WA_DIM    A_DIM
#define WA_BOLD   A_BOLD

#if 1
#define WA_ITALIC A_ITALIC  /* ncurses extension */
#endif
```

so....what on earth could be going on here? It's a mystery to me :/.

**Comment by dankamongmen** [comment] 2020-11-07 10:17
Anything get found out here? Were you ever able to build? Any ideas as to how I might reproduce this?

**Comment by ask6155** [comment] 2020-11-07 12:02
Well I couldn't get it working with pacman (I did a lot of file corruption checks and they all came out negative)
I ended up using nix-shell to build notcurses.
You should package notcurses for nixos since those packages can't get corrupted by stupid mistakes people like me make.
Also maybe include a nix file in the repo so that there can be a reproducible build environment.

**Comment by dankamongmen** [comment] 2020-11-18 04:59
> Well I couldn't get it working with pacman (I did a lot of file corruption checks and they all came out negative)
> I ended up using nix-shell to build notcurses.
> You should package notcurses for nixos since those packages can't get corrupted by stupid mistakes people like me make.
> Also maybe include a nix file in the repo so that there can be a reproducible build environment.

I definitely plan to, but I don't have a Nix machine handy.

It's so weird that you couldn't get it going on arch! I don't understand at all how that's happening. It really does befuddle me.

BTW, don't think you're stupid at all =]. I'm going to go ahead and close this as a NONFIX. If you get any more information or insight, please do let me know. Sorry I couldn't help you :/.

**Closed by dankamongmen** 2020-11-18 04:59 UTC
Labels: bug, nonfix
