### ISSUE TITLE
how to render a plane not bounded to the stdplane, possible bug?

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1732] opened 2021-06-07 18:53 UTC
I'm trying to render planes without using the standard plane... without success. I just want to check I'm not misunderstanding something...

To show the stdplane I just need to set its base channels and call notcurses_render.

But in order to show a new unbound plane, it seems not enough to set its base channels, then call ncpile_render and ncpile_raster, and then notcurses_render... because nothing shows, at all.

I've created [an example](https://github.com/dankamongmen/notcurses/blob/master/rust/examples/issue-1732.rs).

**Comment by dankamongmen** [comment] 2021-06-07 19:14
a few things here:

1) you *either* call (`ncpile_render()` + `ncpile_raster()`), *or* `notcurses_render()`. `notcurses_render()` is just `ncpile_render()` + `ncpile_raster()` called on the standard pile (the pile containing the standard plane).

2) you don't "render" a plane -- i'm not quite sure what you mean here. do you mean just make it show up? you render *piles* (stacks of planes). a rendering operation generates ("solves") a frame from a set of piles. rasterizing this frame converts it to escape codes and glyphs, which are then written out.

i'll go take a look at your code

**Comment by dankamongmen** [comment] 2021-06-07 19:21
`    let chan_blue = NcChannelPair::with_rgb(0x88aa00, 0x2222287);` is 0x22222287 intended here? it seems two too many hex digits

**Comment by dankamongmen** [comment] 2021-06-07 19:23
ok so you're here making a second pile, with two planes in it, `plane1` and `plane2`, got it

**Comment by dankamongmen** [comment] 2021-06-07 19:27
![2021-06-07-152714_1072x1417_scrot](https://user-images.githubusercontent.com/143473/121076831-d9f1d280-c7a4-11eb-85c4-715dd5fb775d.png)

```c
#include <notcurses/notcurses.h>                                                                           
                                                                                                           
int main(void){                                                                                            
  uint64_t blue = CHANNELS_RGB_INITIALIZER(0x88, 0xaa, 0, 0x22, 0x22, 0x87);                               
  uint64_t green = CHANNELS_RGB_INITIALIZER(0x22, 0x44, 0x11, 0x22, 0x99, 0x22);                           
  struct notcurses* nc = notcurses_init(NULL, NULL);                                                       
  if(nc == NULL){                                                                                          
    return EXIT_FAILURE;                                                                                   
  }                                                                                                        
  struct ncplane_options nopts = {                                                                         
    .rows = 20,                                                                                            
    .cols = 40,                                                                                            
  };                                                                                                       
  struct ncplane* p1 = ncpile_create(nc, &nopts);                                                          
  if(p1 == NULL){                                                                                          
    goto err;                                                                                              
  }                                                                                                        
  ncplane_set_base(p1, "1", 0, blue);                                                                      
  if(ncpile_render(p1)){                                                                                   
    goto err;                                                                                              
  }                                                                                                        
  if(ncpile_rasterize(p1)){                                                                                
    goto err;                                                                                              
  }                                                                                                        
sleep(5);                                                                                                  
  notcurses_stop(nc);                                                                                      
  return EXIT_SUCCESS;                                                                                     
                                                                                                           
err:                                                                                                       
  notcurses_stop(nc);                                                                                      
  return EXIT_FAILURE;                                                                                     
}   
```

**Comment by dankamongmen** [comment] 2021-06-07 19:30
![2021-06-07-152959_1072x1417_scrot](https://user-images.githubusercontent.com/143473/121077129-3c4ad300-c7a5-11eb-803d-f4de414b668d.png)

```c
[schwarzgerat](0) $ cat ../src/poc/piles.c 
#include <notcurses/notcurses.h>

int main(void){
  uint64_t blue = CHANNELS_RGB_INITIALIZER(0x88, 0xaa, 0, 0x22, 0x22, 0x87);
  uint64_t green = CHANNELS_RGB_INITIALIZER(0x22, 0x44, 0x11, 0x22, 0x99, 0x22);
  struct notcurses* nc = notcurses_init(NULL, NULL);
  if(nc == NULL){
    return EXIT_FAILURE;
  }
  struct ncplane_options nopts = {
    .rows = 20,
    .cols = 40,
  };
  struct ncplane* p1 = ncpile_create(nc, &nopts);
  if(p1 == NULL){
    goto err;
  }
  ncplane_set_base(p1, "1", 0, blue);
  if(ncpile_render(p1)){
    goto err;
  }
  if(ncpile_rasterize(p1)){
    goto err;
  }
sleep(2);
  nopts.rows = 2;
  nopts.cols = 4;
  struct ncplane* p2 = ncplane_create(p1, &nopts);
  if(p2 == NULL){
    goto err;
  }
  ncplane_set_base(p2, "2", 0, green);
  if(ncpile_render(p1)){
    goto err;
  }
  if(ncpile_rasterize(p1)){
    goto err;
  }
sleep(2);
  notcurses_stop(nc);
  return EXIT_SUCCESS;

err:
  notcurses_stop(nc);
  return EXIT_FAILURE;
}
[schwarzgerat](0) $ 
```

**Comment by dankamongmen** [comment] 2021-06-07 19:42
so this, in my mind, demonstrates what you're trying to do, and that it works...i commented out the intermediate render+raster, just to make sure that wasn't it, and got the expected result. i can confirm that your rust example `issue-1732` doesn't display them, though. i can try to debug from the other end, if the code i just provided hasn't made things obvious.

**Comment by joseluis** [comment] 2021-06-07 20:00
thank you nick, that's very usefuk, so there must be an error in the rust bindings then... I'll check it out, probably tomorrow

**Comment by joseluis** [comment] 2021-06-08 08:34
Ok this is what I've found:

1. the unbounded pile shows if instead of calling notcurses_render I call ncpile_render and ncpile_rasterize

2. it stops showing as soon as I call notcurses_render

I don't think this is a bug of the rust bindings

**Comment by dankamongmen** [comment] 2021-06-08 08:39
> Ok this is what I've found:
> 
> 1. the unbounded pile shows if instead of calling notcurses_render I call ncpile_render and ncpile_rasterize
> 2. it stops showing as soon as I call notcurses_render
> 
> I don't think this is a bug of the rust bindings

no, see what i said above:

> you either call (ncpile_render() + ncpile_raster()), or notcurses_render(). notcurses_render() is just ncpile_render() + ncpile_raster() called on the standard pile (the pile containing the standard plane).

so you have two piles here: the standard pile, with the standard plane, and the pile you created when you created the unbound plane, containing p1 and p2.

`notcurses_render()` runs on the standard plane. always. take a look at it:

```c
int notcurses_render(notcurses* nc){                                                                       
  ncplane* stdn = notcurses_stdplane(nc);
  if(ncpile_render(stdn)){                                                     
    return -1;                                                                         
  }                                                                                         
  int i = ncpile_rasterize(stdn);
  return i;
}
```

so `notcurses_render()` is **never** going to show anything but the standard pile.

**Comment by joseluis** [comment] 2021-06-08 08:39
In fact, rendering and rasterizing the standard plane, is what causes the other pile to not show, or even unshow, if it was shown before

**Comment by joseluis** [comment] 2021-06-08 08:40
> notcurses_render() runs on the standard plane. always. take a look at it:

aaaaah... so the standard plane impedes showing the other piles? I didn't know that....

**Comment by dankamongmen** [comment] 2021-06-08 08:42
only one pile is visible at a time, because only one frame is visible at a time, and a frame is a complete definition of the visible state. when you rasterize a frame, you blow away the current content.

if you want all three planes visible, they need be in the same pile.

**Comment by joseluis** [comment] 2021-06-08 08:44
> only one pile is visible at a time, because only one frame is visible at a time, and a frame is a complete definition of the visible state. when you rasterize a frame, you blow away the current content.
> 
> if you want all three planes visible, they need be in the same pile.

Ok this is super-important information that I wasn't aware of before... If that's not in the docs, it definitely should be...

**Comment by dankamongmen** [comment] 2021-06-08 08:46
i think it's in there, but kinda scattered.

from `notcurses(3)`:

```
   Ncpiles
       A given notcurses context is made up of one or more piles.  Piles provide distinct rendering con‐
       texts: a thread can be rendering or mutating one pile, while another thread concurrently  renders
       or  mutates another pile.  A pile is made up of planes, totally ordered on a z-axis.  In addition
       to the z-ordering, the planes of a pile are bound  in  a  forest  (a  set  of  directed,  acyclic
       graphs).   Those  planes  which are not bound to some other plane constitute the root planes of a
       pile.  A pile is destroyed when all its planes are destroyed, or moved to other piles.  Since the
       standard  plane  (see  below) always exists, and cannot be moved to another pile, one pile always
       exists, known as the standard pile.
```

but that doesn't make explicit that they're exclusive visually. that's in `notcurses_render(3)`:

```
DESCRIPTION
       Rendering reduces a pile of ncplanes to a single plane, proceeding from the  top  to  the  bottom
       along  a  pile's  z-axis.   The  result is a matrix of nccells (see notcurses_cell).  Rasterizing
       takes this matrix, together with the current state of the visual area, and produces a  stream  of
       optimized  control  sequences and EGCs for the terminal.  By writing this stream to the terminal,
       the physical display is synced to some pile's planes.

       ncpile_render performs the first of these tasks for the pile of which n is a part.  The output is
       maintained  internally; calling ncpile_render again on the same pile will replace this state with
       a fresh render.  Multiple piles can be concurrently rendered.  ncpile_rasterize performs rasteri‐
       zation, and writes the result to the terminal.  It is a blocking call, and only one rasterization
       operation may proceed at a time.  It does not destroy the render output, and can be called multi‐
       ple  times  on the same render.  notcurses_render calls ncpile_render and ncpile_rasterize on the
       standard plane, for backwards compatibility.  It is an exclusive blocking call.

       It is necessary to call ncpile_rasterize or notcurses_render to generate any visible output;  the
       various  notcurses_output(3) calls only draw to the virtual ncplanes.  Most of the notcurses sta‐
       tistics are updated as a result of a render (see notcurses_stats(3)), and screen geometry is  re‐
       freshed (similarly to notcurses_refresh(3)) following the render.
```

**Comment by dankamongmen** [comment] 2021-06-08 08:56
the way to understand this -- as is the case, hopefully, whenever you encounter a seemingly unnecessarily convoluted concept in Notcurses -- is through a focus on peak performance.

to take advantage of parallelism, we need be able to do work on an upcoming frame while another thread renders/rasterizes the current one. that way, the next frame can be available with minimum latency upon completion of the writeout. ideally (assuming continuous change) we would be writing 100% of the time, i.e. as fast as the terminal can accept and display our updates. a single thread cannot reliably achieve this if there is non-negligible work per frame.

so if we want multiple threads, we need to break up the work. each thread will need its own concept of what ought be on screen, so there's no point in carrying state across rendering contexts--rasterization must be a prescriptive, not normative, operation.

if you instead wanted two threads to work within a rendering context, you'd need partition the data among planes, which can be safely concurrently mutated. again from `notcurses(3)`:

```c
   Threads
       Notcurses explicitly supports use in multithreaded environments, but it does not  itself  perform
       any locking.

       • Only  one pile's rendered frame can be rasterized at a time, and it is not safe to concurrently
         render that pile.  It is safe to rasterize a frame while rendering some other pile.

       • It is otherwise always safe to operate concurrently on distinct piles.

       • It is not safe to render a pile while concurrently modifying that pile.

       • It is safe to output to multiple distinct ncplanes at the same time, even within the same pile.

       • It is safe to output to ncplanes while adding or deleting some other ncplane.

       • It is not safe for multiple threads to output to the same ncplane.

       • It is not safe to add, delete, or reorder ncplanes within a single pile from multiple threads.

       Only one thread may call notcurses_getc or any other input-related thread at a time,  but  it  is
       safe to call for input while another thread renders.

       Since  multiple threads can concurrently manipulate distinct ncplanes, peak performance might re‐
       quire dividing the screen into several planes, and manipulating them from multiple threads.
```

**Comment by dankamongmen** [comment] 2021-06-08 09:05
https://www.youtube.com/watch?v=aEmJf_uC2l0

**Comment by joseluis** [comment] 2021-06-08 09:07
> i think it's in there, but kinda scattered.

Now that I read those paragraphs again I'm understand the implications now that I don't know how I didn't get the first time.

Also I have to admit the scattered information has always been a PITA... I always missed having a complete reference in a single place, instead of multiple places where to fish por possible complementary pieces of information, I think that's why started putting so much effort in the Rust binding docs. And even then I keep discovering basic things like this that I didn't really understand correctly...

I think the meaning I had in my mind to the words "context" and "render" in the context of notcurses, it wasn't the same as it is now that I undestand better how this works in a practical example.

**Comment by dankamongmen** [comment] 2021-06-08 09:08
> https://www.youtube.com/watch?v=aEmJf_uC2l0

kickin' down the doors of Valhalla looking for Elián González, wu-hah!

> Also I have to admit the scattered information has always been a PITA... I always missed having a complete reference in a single place, instead of multiple places where to fish por possible complementary pieces of information, I think that's why started putting so much effort in the Rust binding docs. And even then I keep discovering basic things like this that I didn't really understand correctly...

lol i assure you writing even this level of documentation has likewise always been a PITA

we will release 3.0.0, and then i will go back and update the increasingly-out-of-date book

**Comment by dankamongmen** [comment] 2021-06-08 09:10
also, relying on the reader to grok all your implications is a fool's errand. i honestly just overlooked making this explicit. PRs warmly welcomed, or i will figure out a way to write up this info

**Comment by dankamongmen** [comment] 2021-06-09 07:34
> > note that when #1615 is in place, you'll be able to have different margins for different piles, and thus you could have overlap (rasterizing doesn't blow away material in your margins; that's the whole point of margins).
> 
> omg... I'm gonna have to create a good example in rust to fully undestand this pile/plan model once and for all.

i mean, i do not expect piles with different margins to be a common case or anything. i don't expect piles to be a common thing, period -- the vast majority of programs will use only the standard pile. but who knows what people will do if you give them capabilities?

**Comment by dankamongmen** [comment] 2021-06-09 07:35
so i've updated the documentation to make this all a bit more explicit. feel free to reopen if you want to track your rust example with this, but i'm closing it otherwise.

**Closed by dankamongmen** 2021-06-09 07:35 UTC
Labels: documentation, userquestion
