### ISSUE TITLE
incorrect sexblitter rendering in alacritty

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1099] opened 2020-11-05 11:47 UTC
Taken after removing my alacritty configuration to make sure it was not caused by it.

using alacritty 0.5 (current stable) (looks distorted in a similar way as kitty 0.15):
![alacritty 0 5 sexblitter](https://user-images.githubusercontent.com/5832068/98236959-7381a900-1f64-11eb-8d3c-7629671ca6f9.png)

using alacritty 0.6-dev (latest from master):
![alacritty 0 6 sexblitter](https://user-images.githubusercontent.com/5832068/98236971-78465d00-1f64-11eb-9cd5-46df81533914.png)

using xfce4-terminal 0.8.9.1 (looks the same with kitty 0.19.1):
![xfce4-terminal 0 8 9 1 sexblitter](https://user-images.githubusercontent.com/5832068/98237008-87c5a600-1f64-11eb-941d-694a616e795f.png)

reference image:
![pic](https://user-images.githubusercontent.com/5832068/98237022-8b592d00-1f64-11eb-9822-57cfab4491d3.jpg)

**Comment by dankamongmen** [comment] 2020-11-05 18:47
Thanks for the heads-up. So if I read this correctly, we're only talking the alacritty 0.6-pre, right? The 0.5 image looks pretty much correct to me.

If so, I'll go ahead and pull alacritty from head and see what's up. I've got a decent working relationship with some of the people on that team.

**Comment by joseluis** [comment] 2020-11-05 18:56
The 0.5 image is bad too, (distorted in a similar way kitty 0.15 does as we discussed earlier). Sorry I didn't notice it doesn't show in the thumbnail, you have to take a look at the linked full sized version to appreciate it.

**Comment by dankamongmen** [comment] 2020-11-05 19:12
OK. I've definitely noticed problems with sexblitter in alacritty, as well. I think it's not displaying the sextant glyphs correctly. Here's a screenshot of vim with `blit.c` open in alacritty 0.5. Note how, for instance, the quotation marks closing each EGC stomp atop the sextant glyphs' right hand side.

![2020-11-05-141216_720x690_scrot](https://user-images.githubusercontent.com/143473/98285687-ec86fd80-1f70-11eb-9e83-8cbef97719ad.png)

**Comment by dankamongmen** [comment] 2020-11-12 14:29
I'm gonna file a bug against alacritty shortly. From a look into its source, they're doing something special for block characters like this, but I don't quite understand it, and don't have a ton of time to go rooting around in Other People's Source in the near future. Hopefully they can get this resolved.

**Comment by dankamongmen** [comment] 2020-11-12 15:14
https://github.com/alacritty/alacritty/issues/4409

**Comment by kchibisov** [comment] 2020-11-12 15:29
@joseluis Could you bisect alacritty or a provide me a way to reproduce the change from 0.5.0 stable to 0.6.0-dev in alacritty? I'm not sure that we(alacritty) have changed anything that could affect that at all.

**Comment by joseluis** [comment] 2020-11-12 16:40
@kchibisov I've been trying for the past hour to compile a version that replicates the old behaviour without success...

Either through `cargo install alacritty`, or from [this commit from Aug 1st in master](https://github.com/alacritty/alacritty/commit/5c8aa679ae27390d18c2e90134f5fdfe5918c07a), or downloading the 0.5 release tar.gz, (both using the current rustc stable version, the minimum supported version of 1.41.0 and last nightly), but it makes no difference at all. They all look like this:

![Kazam_screenshot_00000](https://user-images.githubusercontent.com/5832068/98965604-8834e280-250a-11eb-9190-3e943aa5b0a5.png)

Weirdly enough I still have the v0.5 alacritty binary that shows the sexblittered image like this (compiled months ago with `cargo install` I believe, since I renamed it alacritty-0.5 in my ~/cargo/bin/):

![Kazam_screenshot_00001](https://user-images.githubusercontent.com/5832068/98968284-c253b380-250d-11eb-97f0-1c8975acf23b.png)

I don't understand why this happens. Let me know if I can do anything more for you.

**Comment by kchibisov** [comment] 2020-11-12 16:43
@joseluis I'd suggest you to bisect with just `cargo run`. if you'll be able to find the commit that change it, I'd be curios to look why it got changed, checking versions before `v0.5.0` is also fine.

**Comment by joseluis** [comment] 2020-11-12 17:11
> checking versions before v0.5.0 is also fine.

@kchibisov Ok! I found the first bad commit at 0.4.1-dev. Compiling the previous commit to this shows the image like the second previous one.

https://github.com/alacritty/alacritty/commit/88b4dbfc5a890569fcfac3fe400fe0ad0ea234cc

**Comment by kchibisov** [comment] 2020-11-12 17:16
@joseluis that shouldn't matter, since this code only compiles on windows, try something before?

**Comment by joseluis** [comment] 2020-11-12 17:18
Yeah... I was wondering why that commit was insustantial... I'm gonna repeat it this time running cargo clean before cargo run...

**Comment by joseluis** [comment] 2020-11-12 17:55
@kchibisov It was the next commit, sorry, first time using bisect :sweat_smile: 

https://github.com/alacritty/alacritty/commit/79b19176eeb57fbd6b137160afd6bc9f5518ad33

now this makes more sense...

**Comment by kchibisov** [comment] 2020-11-12 17:58
Could you tell me what to run to repro it?

**Comment by dankamongmen** [comment] 2020-11-12 18:14
> Could you tell me what to run to repro it?

if you mean what to run inside of such an alacritty, i would recommend `notcurses-view -b sexblitter [someimage]`.

**Comment by kchibisov** [comment] 2020-11-12 18:16
>if you mean what to run inside of such an alacritty, i would recommend notcurses-view -b sexblitter [someimage].

thx, also link to that image could help, so I'll run the same thing.

**Comment by joseluis** [comment] 2020-11-12 18:44
@kchibisov 

> Could you tell me what to run to repro it?

`notcurses-view -b sexblitter ./test-pic.jpg`

> thx, also link to that image could help, so I'll run the same thing.

this is the original image:
https://user-images.githubusercontent.com/5832068/98237022-8b592d00-1f64-11eb-9822-57cfab4491d3.jpg

ideally it should look like this through the terminal:
https://user-images.githubusercontent.com/5832068/98237008-87c5a600-1f64-11eb-941d-694a616e795f.png


Finally, this is the script I made to recompile & install notcurses, from the parent directory, JIC:
```sh
#!/bin/sh
# dependencies for ubuntu:
# build-essential gcc libavcodec-dev libavformat-dev libswscale-dev libncursesw5-dev doctest-dev libunistring-dev libqrcodegen-dev cmake pandoc libclang-dev

# download repo
# git clone https://github.com/dankamongmen/notcurses/

# recompile

cd notcurses/

rm -rf build/
mkdir -p build
cd build/

cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ ..

make -j6
#make test

echo -e "now please run:\ncd notcurses/build; sudo make install; cd -"
```

After that you'll be able to call `notcurses-view`

**Comment by dankamongmen** [comment] 2020-11-12 18:57
> # build-essential gcc libavcodec-dev libavformat-dev libswscale-dev libncursesw5-dev doctest-dev libunistring-dev libqrcodegen-dev cmake pandoc libclang-dev

does your ubuntu really not have ncurses6? on debian i just use `libncurses-dev`:

```
Package: libncurses-dev
Version: 6.2+20200918-1
```

**Comment by joseluis** [comment] 2020-11-12 19:08
> does your ubuntu really not have ncurses6? on debian i just use `libncurses-dev`:

hmmm it's a transitional package in my case, so I'm also using v6... I'll update my dependencies list :grin:

**Comment by kchibisov** [comment] 2020-11-12 19:20
@joseluis I can't repro, however I don't know what glyph is being used for foreground, since all the glyphs for me are missing, and only background is rendered. 

![picture](https://user-images.githubusercontent.com/27620401/98985738-0c03c480-2535-11eb-8a96-fc6485dfaeca.png)

When using small font sizes it looks like 

![picture](https://user-images.githubusercontent.com/27620401/98985834-2b9aed00-2535-11eb-8ea7-ce8097642b4e.png)

Maybe the font which is being used messes things up? Maybe glyphs are actually some weird emojis...

**Comment by joseluis** [comment] 2020-11-12 19:27
@kchibisov  This font has all the shapes https://www.babelstone.co.uk/Fonts/Shapes.html

**Comment by kchibisov** [comment] 2020-11-12 19:57
Ok, it seems like the font you've linked has colored tables, thus freetype identifies it as colored font, so alacritty uses different code patch in font loading library for colored glyphs and sets size setting for colored glyphs with freetype completely differs from normal characters, so that's why normal characters, which this font actually has for whatever reason, fail to render at all, since the size setting for them doesn't work (you can't even mix/match them...).

So you can close this bug and I'll open one on alacritty's font library  tracker.

**Comment by kchibisov** [comment] 2020-11-12 19:59
alacritty related bug https://github.com/alacritty/crossfont/issues/17

**Comment by kchibisov** [comment] 2020-11-12 20:00
In general if you want to work around this issue in your setup, I'd suggest to use font that doesn't mix colored and normal glyphs for now...

**Comment by dankamongmen** [comment] 2020-11-12 20:23
FWIW, I do not believe that I am using said font. I'll look into mine (I'm not even sure exactly how fallback works, so I need educate myself on that), where I'm also seeing issues (distinct from and rather less catastrophic than those of @joseluis ).

**Comment by dankamongmen** [comment] 2020-11-12 20:26
As noted by @kchibisov , it looks like this is a problem in the dreaded font stack, and out of our hands. Closing as NONFIX. Truly, font madness will be the end of me. Thanks for doing the hard work, @joseluis and @kchibisov !

**Closed by dankamongmen** 2020-11-12 20:26 UTC
Labels: nonfix
