### ISSUE TITLE
Input event showing inconsistent behaviour

### ISSUE THREAD

**Issue by CyanideForBreakfast** [dankamongmen/notcurses#2517] opened 2021-12-30 13:22 UTC
Hey, I've been messing around with examples and it appears that it is showing inconsistent behavior when using taking input from the user.

### Details
| Type | Value |
| --- | --- |
| OS | Arch |
| Window Manager | XMonad (X11) |
| Notcurses version | 3.0.2 (from AUR notcurses-git) |

 ### Code
examples/input.rs
```
use libnotcurses_sys::*;

fn main() -> NcResult<()> {
    let nc = unsafe { Nc::with_flags(NcOptions::SUPPRESS_BANNERS)? };
    let splane = unsafe { nc.stdplane() };
    splane.set_scrolling(true);

    putstrln!(splane, "Input example.\nPress any key to continue:")?;
    nc.render()?;
    let rec = nc.get_blocking(None)?;
    putstrln!(splane, "Received: {:?}\n", rec)?;

    putstrln!(
        splane,
        "Press more keys to see their input. You can exit with F1.\n"
    )?;

    let mut input = NcInput::new_empty();
    loop {
        let rec = nc.get_nblock(Some(&mut input))?;
        match rec {
            NcReceived::Char(ch) => {
                putstrln!(
                    splane,
                    "char: '{0}' \n{1:?} {2:?}\n",
                    ch,
                    input,
                    input.char()
                )?;
            }
            NcReceived::Event(ev) => {
                putstrln!(
                    splane,
                    "event: {0:?}\n  {1:?} {2:?}\n",
                    ev.name(),
                    input,
                    input.char()
                )?;
                match ev {
                    NcKey::F01 => break,
                    _ => (),
                }
            }
            NcReceived::Other(o) => {
                putstrln!(
                    splane,
                    "other (this shouldn't happen): {0:?} \n{1:?}\n",
                    o,
                    input
                )?;
            }
            _ => (),
        }
    }

    unsafe { nc.stop()? };
    Ok(())
}
```

#### Alacritty
When pressed any character with Shift key, the character received is capitalized (in comparison to lowercase character received when pressed without Shift) which can be mostly workable but gets confusing when something like Ctrl + Shift + Y is passed, which I'm not able to distinguish from Ctrl + Y from the `NcRecieved` and `NcInput` value, because the `shift` value is `false` for both of them.

#### Kitty
Kitty detects each input twice. Also, it detects key-presses like LCTRL which are not detect in Alacritty or Xterm though in here we do get the `shift` value as `true` when Shift is held.

#### Xterm
Just like Alacritty `shift` value is unaffected even if Shift is pressed. Also, (on my system atleast), I get a bunch of garbage random input events when I first `cargo run` my program.

**Comment by dankamongmen** [comment] 2022-01-01 19:13
alright, looking at `xterm_err.log`, i'm not sure i'm seeing any actual input being processed...here's the end of terminal responses, terminating in the DA1:

```
process_escape:1871:walk result on 56 (8): 0 348                                                                                    
da1_attrs_cb:1068:read primary device attributes                                                                                    
da1_attrs_cb:1071:DA1: 64 [1;2;6;9;15;16;17;18;21;22;28]                                                                            
process_escape:1871:walk result on 99 (c): 1 347                                                                                    
handoff_initial_responses_late:1014:handing off initial responses                                                                   
block_on_input:2127:blocking on input availability                                                                                  
block_on_input:2184:waiting on 1 fds (ibuf: 0/8192)                                                                                 
ncplane_new_internal:658:created new 55x212 plane "std" @ 0x0                                                                       
engorge_crender_vector:1553:resizing rvec (0) for 0x5634a05e9150 to 11660                                                           
notcurses_rasterize_inner:1273:pile 0x5634a05e9150 ymax: 55 xmax: 212    
```

we're then in the main loop, but we don't see any further input...hrm.

i'm looking through the previous material, and everything looks like terminal responses...we've got (backwards to the beginning) DA1, cell geom report, pixel geom report, ahhh!!!

```
process_escape:1871:walk result on 121 (y): 2 314                                                                                   
process_melange:2043:input 3113 (0)/81 [0x1b] ( )                                                                                   
process_escape:1859:initialized automaton to 1                                                                                      
process_escape:1871:walk result on 91 ([): 0 4                                                                                      
process_escape:1871:walk result on 63 (?): 0 304                                                                                    
process_escape:1871:walk result on 49 (1): 0 316                                                                                    
process_escape:1871:walk result on 59 (;): 0 317                                                                                    
process_escape:1871:walk result on 51 (3): 0 322                                                                                    
walk_automaton:569:unexpected transition on 322[83]                                                                                 
process_escape:1871:walk result on 83 (S): -1 0                                                                                     
process_melange:2043:input 3114 (0)/80 [0x5b] ([)                                                                                   
process_melange:2043:input 3115 (0)/79 [0x3f] (?)                                                                                   
process_melange:2043:input 3116 (0)/78 [0x31] (1)                                                                                   
process_melange:2043:input 3117 (0)/77 [0x3b] (;)                                                                                   
process_melange:2043:input 3118 (0)/76 [0x33] (3)                                                                                   
process_melange:2043:input 3119 (0)/75 [0x53] (S)                                                                                   
process_melange:2043:input 3120 (0)/74 [0x1b] ( )                                                                                   
process_escape:1859:initialized automaton to 1                                                                                      
process_escape:1871:walk result on 91 ([): 0 4                                                                                      
process_escape:1871:walk result on 63 (?): 0 304                                                                                    
process_escape:1871:walk result on 50 (2): 0 307                                                                                    
process_escape:1871:walk result on 59 (;): 0 326                                                                                    
process_escape:1871:walk result on 51 (3): 0 331                                                                                    
walk_automaton:569:unexpected transition on 331[83]                                                                                 
process_escape:1871:walk result on 83 (S): -1 0                                                                                     
process_melange:2043:input 3121 (0)/73 [0x5b] ([)                                                                                   
process_melange:2043:input 3122 (0)/72 [0x3f] (?)                                                                                   
process_melange:2043:input 3123 (0)/71 [0x32] (2)                                                                                   
process_melange:2043:input 3124 (0)/70 [0x3b] (;)                                                                                   
process_melange:2043:input 3125 (0)/69 [0x33] (3)                                                                                   
process_melange:2043:input 3126 (0)/68 [0x53] (S)                                                                                   
process_melange:2043:input 3127 (0)/67 [0x1b] ( )                                                                                   
process_escape:1859:initialized automaton to 1                                                                                      
process_escape:1871:walk result on 91 ([): 0 4                                                                                      
process_escape:1871:walk result on 63 (?): 0 304                                                                                    
process_escape:1871:walk result on 49 (1): 0 316                                                                                    
process_escape:1871:walk result on 59 (;): 0 317                                                                                    
process_escape:1871:walk result on 51 (3): 0 322                                                                                    
walk_automaton:569:unexpected transition on 322[83]                                                                                 
process_escape:1871:walk result on 83 (S): -1 0                                                                                     
process_melange:2043:input 3128 (0)/66 [0x5b] ([)                                                                                   
process_melange:2043:input 3129 (0)/65 [0x3f] (?)                                                                                   
process_melange:2043:input 3130 (0)/64 [0x31] (1)                                                                                   
process_melange:2043:input 3131 (0)/63 [0x3b] (;)                                                                                   
process_melange:2043:input 3132 (0)/62 [0x33] (3)                                                                                   
process_melange:2043:input 3133 (0)/61 [0x53] (S)                                                                                   
process_melange:2043:input 3134 (0)/60 [0x1b] ( )                                                                                   
process_escape:1859:initialized automaton to 1                                                                                      
process_escape:1871:walk result on 91 ([): 0 4      
```

look at this garbage! ok so these are XTSMGRAPHICS replies indicating failures, iirc. and we apparently don't process these all the way through, and thus they get replayed as keyboard input. well, that ought be easy enough to test and fix, if so.

**Comment by dankamongmen** [comment] 2022-01-01 19:14
and indeed you are lacking the `4` in DA1 which would indicate sixel support. so it looks like the garbage is going to happen on any xterm which doesn't support sixel. alright, testing...

**Comment by dankamongmen** [comment] 2022-01-01 19:18
tally-ho! i reconfigured XTerm without 

```
!XTerm*decGraphicsID: 340                                                                                                           
!XTerm*decTerminalID: 420 
```

thus disabling sixel. I then ran `notcurses-input`, and elicited:

```
 acsu ASCII: [0x1b (027)] '␛'                                                
  acsu ASCII: [0x5b (091)] '['                                                
  acsu ASCII: [0x3f (063)] '?'                                                
  acsu ASCII: [0x31 (049)] '1'                                                
  acsu ASCII: [0x3b (059)] ';'                                                
  acsu ASCII: [0x33 (051)] '3'                                                
  acsu ASCII: [0x53 (083)] 'S'                                                
  acsu ASCII: [0x1b (027)] '␛'                                                
  acsu ASCII: [0x5b (091)] '['                                                
  acsu ASCII: [0x3f (063)] '?'                                                
  acsu ASCII: [0x31 (049)] '1'                                                
  acsu ASCII: [0x3b (059)] ';'                                                
  acsu ASCII: [0x33 (051)] '3'                                                
  acsu ASCII: [0x53 (083)] 'S'                                                
  acsu ASCII: [0x1b (027)] '␛'                                                
  acsu ASCII: [0x5b (091)] '['                                                
  acsu ASCII: [0x3f (063)] '?'                                                
  acsu ASCII: [0x32 (050)] '2'                                                
  acsu ASCII: [0x3b (059)] ';'                                                
  acsu ASCII: [0x33 (051)] '3'                                                
  acsu ASCII: [0x53 (083)] 'S'                                                
  acsu ASCII: [0x1b (027)] '␛'                                                
  acsu ASCII: [0x5b (091)] '['                                                
  acsu ASCII: [0x3f (063)] '?'                                                
  acsu ASCII: [0x31 (049)] '1'                                                
  acsu ASCII: [0x3b (059)] ';'                                                
  acsu ASCII: [0x33 (051)] '3'                                                
  acsu ASCII: [0x53 (083)] 'S'     
```

so thius is reproduced, and ought be fixed very soon.

**Comment by dankamongmen** [comment] 2022-01-01 19:20
so we need handle `\e[?1;3S` and `\e[?2;3S`, it appears?

**Comment by dankamongmen** [comment] 2022-01-01 19:20
yep, that fixes it! w00t!

**Comment by dankamongmen** [comment] 2022-01-01 19:21
ok, so all that remains is the disambiguation of shift vs capitals under XTMODKEYS. let's see what can be done...

**Comment by dankamongmen** [comment] 2022-01-01 19:32
so with `XTMODKEYS` fully engaged, here's what we get in terms of raw input:

```
block_on_input:2217:poll returned 1                                             
block_on_input:2231:got events: tI                                              
read_input_nblock:1828:read 1B from 0 (8191B left)                              
process_melange:2049:input 0 (0)/1 [0x79] (y)                                   
block_on_input:2133:blocking on input availability                              
block_on_input:2190:waiting on 1 fds (ibuf: 0/8192)                             
internal_get:2372:draining event readiness pipe 0   
...
block_on_input:2217:poll returned 1                                             
block_on_input:2231:got events: tI                                              
read_input_nblock:1828:read 1B from 0 (8191B left)                              
process_melange:2049:input 0 (0)/1 [0x59] (Y)                                   
block_on_input:2133:blocking on input availability                              
block_on_input:2190:waiting on 1 fds (ibuf: 0/8192)                             
internal_get:2372:draining event readiness pipe 0  
...
```

here's `strace` output ('y', shift+'y', ctrl+'y', ctrl+shift+'y', shift+'y', ctrl+'d'):

```
pid 1738308] read(0, "y", 8192)        = 1   
[pid 1738308] read(0, "Y", 8192)        = 1   
[pid 1738308] read(0, "\31", 8192)      = 1              
[pid 1738308] read(0, "\31", 8192)      = 1      
[pid 1738308] read(0, "Y", 8192)        = 1       
[pid 1738308] read(0, "\4", 8192)       = 1     
```

so as you can see, ctrl+'y' sends the same thing whether shift is pressed or not: `\31`. there's no way for me to distinguish whether shift is being pressed. likewise, shift+'y' arrives as 'Y', without any other indication. as far as i'm aware, there's no way to XTMODKEYS my way to more detail than this. the Kitty keyboard addresses this (among other things).

unless you can find me another terminal program that *can* distinguish these, or some control sequence which ought make it possible, i simply can't do this (without horrible platform-dependent hooks into the actual input layer, anyway, which wouldn't work over ssh etc.). i must thus regretfully close this bug having only delivered a fix for your xterm barf.

**Comment by dankamongmen** [comment] 2022-01-01 19:32
please let me know if you have any other comments/questions!

**Closed by dankamongmen** 2022-01-01 19:32 UTC
Labels: bug, input

**Comment by CyanideForBreakfast** [comment] 2022-01-02 04:47
Awesome, I don't have any other new issues currently (though I'm interested in fixes to some already opened ones, in particular #2216). Thanks a bunch!

**Comment by dnkl** [comment] 2022-01-02 08:30
@dankamongmen `XTMODKEYS` have two levels; on the first level (which appears to be what you enable in notcurses), many keys still use "legacy" escapes. On the second level, basically everything that involves a modifier becomes a CSI 27 sequence.

So, for e.g. <kbd>Ctrl</kbd>+<kbd>y</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>y</kbd>, we have:

```sh
$ echo  -e '\e[>4;2m' && sudo showkey -a
^[[27;5;121~ 	27 0033 0x1b
 	91 0133 0x5b
 	50 0062 0x32
 	55 0067 0x37
 	59 0073 0x3b
 	53 0065 0x35
 	59 0073 0x3b
 	49 0061 0x31
 	50 0062 0x32
 	49 0061 0x31
 	126 0176 0x7e
^[[27;6;89~ 	27 0033 0x1b
 	91 0133 0x5b
 	50 0062 0x32
 	55 0067 0x37
 	59 0073 0x3b
 	54 0066 0x36
 	59 0073 0x3b
 	56 0070 0x38
 	57 0071 0x39
 	126 0176 0x7e
```
(one of the things the kitty kbd protocol tries to fix can be seen here: the reported _key_ is different in the two examples above - 121 (lower case y), and 89 (upper case y), while at the same time, shift is being encoded into the modifiers).

**Comment by dnkl** [comment] 2022-01-02 08:31
Ref: https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:modifyOtherKeys

**Comment by dankamongmen** [comment] 2022-01-02 19:46
sweet! I'll create a new bug on enabling this for 3.0.4, then. I already parse the sequences, I'm pretty sure, soit ought just be a matter of enabling the extra XTMODKEYS support.
